dpgaspar/Flask-AppBuilder

docs/views.rst
added missing import of render_template need by method3
=> Update views.rst 

flask_appbuilder/static/appbuilder/js/ab_actions.js
Reverts dpgaspar/Flask-AppBuilder#115
=> Revert "bugfix. fix 'multi line confirmation' not display"

flask_appbuilder/templates/appbuilder/general/widgets/direct_chart.html
=> my fix to the multiview bug with charts... this fixes #177

flask_appbuilder/templates/appbuilder/general/model/add.html
Found this typo while greping around.
=> Fixing typo in general/model/add.html

flask_appbuilder/security/registerviews.py
I was able to register users with the same usernames,
=> registration form fields aren't being validated

flask_appbuilder/baseviews.py
=> UTF-8 encoding for the json label strings

flask_appbuilder/views.py
This is work in progress, I need guidance. 
I feel like this almost but there's some magic behind the scene that I don't understand...
=> Making the inline crud stateless

flask_appbuilder/views.py
Somehow I overwrote my original fix with my most recent one. This puts proxy support back into place.
=> Redoing the undone - Proxy support

flask_appbuilder/security/forms.py, flask_appbuilder/security/views.py, flask_appbuilder/templates/appbuilder/general/security/register_oauth.html, flask_appbuilder/translations/de/LC_MESSAGES/messages.po, flask_appbuilder/translations/es/LC_MESSAGES/messages.po, flask_appbuilder/translations/pt/LC_MESSAGES/messages.po, flask_appbuilder/translations/pt_BR/LC_MESSAGES/messages.po, flask_appbuilder/translations/ru/LC_MESSAGES/messages.po, flask_appbuilder/translations/zh/LC_MESSAGES/messages.po
This commit contains fixes for original English strings found during
translation to Polish. This, however, is not a full blown attempt to
fix English in whole project, as this requires more work and more
careful approach to the context.
=> Issue #216 English issues found during translation

flask_appbuilder/models/generic/__init__.py
patch coming from a stackoverflow snippet
=> fixed a bug when ordering view columns where None values are in.

flask_appbuilder/templates/appbuilder/init.html
I'd like to alter the title in my app.
=> Allowing apps to alter title using a jinja block

flask_appbuilder/baseviews.py
Related to https://github.com/dpgaspar/Flask-AppBuilder/issues/317
- The previous behavior would just bubble up exceptions in pre_* BaseView
methods.
- The new behavior flashes the error raised, aborts the operation but does
not fail.
Arguably completely silencing any `Exception` may not be the expected
behavior. An alternative would be to only abort on a specific type of
Exception provided by FAB. Something like a
`FABAbortPreOperationException`. Users would have to raise this specific `Exception` or a
derivative of it. I personally think that this second approach is over
thinking it, the current PR is probably simpler as is.
=> Aborting add/update/delete if pre_add/pre_update/pre_delete raises

flask_appbuilder/translations/zh/LC_MESSAGES/messages.po
Update translations as a Chinese native speaker :)
=> Update Chinese Translations

bin/hash_db_password.py, bin/migrate_db_1.3.py, examples/quickhowto/app/views.py, examples/quickhowto3/app/__init__.py, flask_appbuilder/models/sqla/__init__.py, setup.py
This allows usage of Flask-SQLAlchemy 2.1, see issue #263
=> Fix sqla 2.1

flask_appbuilder/baseviews.py
add_form_query_rel_fields is a dict. While at it update
edit_form_query_rel_fields cut & paste errors.
=> Update add_form_query_rel_fields example to match code

.gitignore, .travis.yml, Dockerfile, README.rst, docker-compose.yml
Using Docker images makes running the test suite a lot easier and would make future contributions more likely, please consider merging it @dpgaspar
=> Combine #371 with #375 to fix the pip issue with Travis CI

docs/customizing.rst
Update the name of the template filename to match the name suggested earlier in the documentation.
=> Improvement to example of custom index view

README.rst
Just wanted to keep the Readme current:
- Renamed the link
- Used Airbnb's project description
PS. FAB is amazing - looking to use it in a project I'm working on ATM.
=> Renaming FAB user, "Caravel" -> "Superset"

.travis.yml, flask_appbuilder/tests/test_base.py, flask_appbuilder/tests/test_mongoengine.py, requirements.txt, setup.py
Upgraded some packages, except flask-alchemy, which needs some core changes, I guess.
Disabled few tests which currently does not work.
Tested on my CI: https://travis-ci.org/S-YOU/Flask-AppBuilder/builds/229644501
=> Fix CI: upgrade pip, deps

flask_appbuilder/security/manager.py
It's fairly simple change makes it easy to login.
=> Added support for users to login with their username or email address

docs/security.rst, flask_appbuilder/security/manager.py, flask_appbuilder/security/views.py, flask_appbuilder/templates/appbuilder/general/security/login_oauth.html
We're using FAB as a Superset dependency and wanted to use OAuth with Google.
This fixes use of deprecated Google+ API call and broken self registration.
=> Fixes for Google OAuth

docs/security.rst, examples/basefilter/config.py, examples/extendsecurity2/config.py, examples/factoryapp/config.py, examples/issue_188/config.py, examples/issue_28/config.py, examples/masterdetail/config.py, examples/mongo_extendedsecurity/config.py, examples/mongoengine/config.py, examples/mongoimages/config.py, examples/oauth/config.py, examples/quickcharts/config.py, examples/quickcharts2/config.py, examples/quickhowto2/config.py, examples/quickhowto3/config.py, examples/quicksqlviews/config.py, examples/quicktemplates/config.py, examples/related_fields/config.py, examples/simpleform/config.py, examples/widgets/config.py, flask_appbuilder/const.py, flask_appbuilder/security/manager.py
=> Ldap use tls

flask_appbuilder/templates/appbuilder/navbar_menu.html
Menu dividers have stopped working for me a while back. I'm not sure what broke it, but this fixes them.
=> Fix missing menu dividers

flask_appbuilder/templates/appbuilder/general/security/login_db.html
sorry I am writing a login_db.html, and find some indent that make me puzzled ,  I think your code is beautifull and conciseness so do some maybe useless change to make others understand the  structure of html
=> change the indent

flask_appbuilder/views.py
in python3, this line will raise 
```
NameError: name 'unicode' is not defined
```
@dpgaspar
=> python3 compatibility fix for unicode

flask_appbuilder/tests/test_base.py, flask_appbuilder/views.py
Also added basic unit test coverage for read, create, and update endpoint of the API
=> [api/update] only update keys specified in POST data

flask_appbuilder/upload.py
I propose to add two methods to FileUploadField, which can be overridden to customize file uploading.
=> FileUploadField: process_on_store() and process_on_delete()

setup.py
fixes https://github.com/apache/incubator-superset/issues/3182
=> Bump flask-babel from 0.10.0 to 0.11.1

examples/quickactions/app/__init__.py, examples/quickactions/app/models.py, examples/quickactions/app/views.py, examples/quickactions/config.py, examples/quickactions/run.py, examples/quickactions/testdata.py
'quickactions' example is not implemented.
As mentioned on #576, the folder only has code related to babel.
The project docs explains the 'Action feature', and has some code in it. This PR creates a simple project that uses the code from the docs.
Fix #576
=> Implement quickactions example

flask_appbuilder/baseviews.py, flask_appbuilder/models/base.py, flask_appbuilder/models/generic/interface.py, flask_appbuilder/models/mongoengine/interface.py, flask_appbuilder/models/sqla/interface.py, flask_appbuilder/tests/test_base.py, flask_appbuilder/views.py
Add composite primary key support for SQLAlchemy
=> Add composite pk support for sqlalchemy

docs/advanced.rst, docs/fabmanager.rst, docs/i18n.rst, docs/security.rst, docs/versionmigration.rst
Documentation change, fix usage of "you're" and one instance of 'yourself'
=> Fix grammar/spelling: your->you're

docs/security.rst
=> docs: fix spelling errors

docs/relations.rst, examples/composite_keys/README.rst, examples/composite_keys/app/__init__.py, examples/composite_keys/app/models.py, examples/composite_keys/app/views.py, examples/composite_keys/config.py, examples/composite_keys/run.py, examples/composite_keys/testdata.py
Simple example to show the use of composite keys, and their reference with SQLA realationships.
Follow up on merged PR #639
=> Docs and example for composite keys

flask_appbuilder/security/sqla/models.py
This PR addresses issue https://github.com/dpgaspar/Flask-AppBuilder/issues/699. 
cc: @mistercrunch
=> [constraints] Adding uniqueness constraints

flask_appbuilder/security/sqla/manager.py
This PR addresses issue https://github.com/dpgaspar/Flask-AppBuilder/issues/683.
cc: @mistercrunch
=> [permissions] Fixing deleting permission check

examples/oauth/README.rst, examples/oauth/config.py, flask_appbuilder/security/manager.py, flask_appbuilder/security/views.py
Lot of enterprises are using Azure AD services. Although, app specific decorator can be used, including it in manager.py will make job easy as parsing jwt response token to get user info is cumbersome.
=> Azure AD as Oauth provider

flask_appbuilder/security/views.py
Somehow my text editor fixed a bunch of empty dangling spaces as well...
=> Fix minor typo EMail -> Email

.coveragerc, .travis.yml, examples/quicktemplates/app/templates/mybase.html, flask_appbuilder/security/manager.py, flask_appbuilder/security/mongoengine/models.py, flask_appbuilder/security/sqla/models.py, flask_appbuilder/security/views.py, flask_appbuilder/templates/appbuilder/baselib.html, flask_appbuilder/templates/appbuilder/navbar_right.html, requirements.txt, setup.py
Flask-login 0.2.11 was released in May 2014. There haven't been many breaking changes since then, and there have been some improvements and bug fixes, so this patch upgrades to >=0.3.0.
cc @mistercrunch
=> Update flask login

examples/__init__.py
This solves https://github.com/dpgaspar/Flask-AppBuilder/issues/831
=> Fix: Removed the examples __init__ file

examples/simpleform/app/templates/404.html, flask_appbuilder/templates/appbuilder/index.html
- Fixes unclosed center tag on html pages.
=> Fix, unclosed center tag on html pages

flask_appbuilder/base.py
=> Fix - add missing import (resolving issue: #890)

docs/security.rst
=> Fix, Corrected a typo

flask_appbuilder/security/sqla/manager.py
Added missing rollback() - no clear reason why this was left out.
=> Fix, update manager.py to fix missing missing session rollback() when user add fails.

flask_appbuilder/security/views.py
Fixes a bug, where the copy role modal window was not showing
=> [ui] Fix, Copy role modal not showing

README.rst, docs/installation.rst
This is a simple change to remove support for python 2.
Next versions will remove support an compatibility
=> New, remove python 2 support

README.rst
=> Add company to Readme

requirements.txt, setup.py
and was not being built properly when built from source. Owner of module
created 0.1.1 version for me and I need this updated here for use upstream.
For Fixes:
=> Dependency Bump - Previous 0.1.0 version pinned here had an invalid character in its name

docs/quickhowto.rst, flask_appbuilder/views.py
Fix wrong deprecation warning version
=> [mvc-api] Fix, deprecation warning version

flask_appbuilder/api/__init__.py, flask_appbuilder/security/manager.py
Make regex builtin Admin role optional
=> [security] Fix, make builtin Admin optional

docs/config.rst, flask_appbuilder/base.py
Fixes app factory, AppBuilder is fully configurable using config keys
=> [appbuilder] Fix, app factory pattern round 2

CHANGELOG.rst, flask_appbuilder/__init__.py
=> New, version 2.1.3

docs/installation.rst
=> Fix, Update minimum required python version for 2.1.1 in Doc/Instalation

docs/multipledbs.rst
Updated the doc to fix the issue of "SyntaxError: invalid syntax".
For Fixes:
=> [docs] Fix, Issue of "SyntaxError: invalid syntax".

CHANGELOG.rst, flask_appbuilder/__init__.py, requirements.txt, setup.py
Improvements and Bug fixes on 2.1.4
--------------------------------------------------
- Fix, #1012 API default resource name must be lower case
- Fix, #1013 Use csrf exempt be default when CSRFProtect is registered has a Flask extension
- Fix, #1007 API Support for property decorated functions has models fields
- Fix, #1002 Permission mapping
- New, #1010 Support for UUID sqlalchemy fields has string fields on WTForms
=> New version 2.1.4

requirements.txt
Remove `requests` from the requirements since new `prison` does not need it anymore.
https://github.com/apache/incubator-superset/pull/7643
=> [deps] Fix, new prison does not depend on requests

flask_appbuilder/api/__init__.py
Following issue #1035
Includes OpenAPI security object on each path if path needs authentication
=> [openapi] Fix, include security on paths

examples/simpleform/app/templates/404.html
=> [examples] Fix, close center tag

setup.py
Fixes bug on setup.py version limits
=> Fix, setup pkg version limits

flask_appbuilder/security/sqla/manager.py
This patch fixes the problem using flask-appbuilder in combination with a MSSQL database.
=> fix sql query containing exists in column clause

CHANGELOG.rst, flask_appbuilder/__init__.py
FAB 2.1.11
Improvements and Bug fixes on 2.1.11
------------------------------------
- Fix, #1092 Has access query fails on MSSQL
=> Bump FAB to 2.1.11

flask_appbuilder/tests/test_base.py, flask_appbuilder/tests/test_mongoengine.py, requirements.txt
bump requirements for Werkzeug and Flask, security issue, CVE-2019-14806
=> [setup] bump requirements for Werkzeug and Flask, security alerts

flask_appbuilder/api/convert.py
Preserve field type for custom properties
=> Fix, return raw to keep field type on custom properties

CHANGELOG.rst, flask_appbuilder/__init__.py
=> Bump FAB to 2.1.13

flask_appbuilder/templates/appbuilder/general/lib.html, flask_appbuilder/templates/appbuilder/general/model/edit.html, flask_appbuilder/templates/appbuilder/general/model/show.html
Also injecting new CSS classes so that we can do some CSS adjustments on the
CRUD forms.
=> [MVC CRUD] New, hide tabs when only 'Detail' (no related_views)

flask_appbuilder/security/sqla/manager.py
=> Fix: Support absence of the public role

flask_appbuilder/models/sqla/interface.py, flask_appbuilder/templates/appbuilder/general/lib.html
Fix for #1127 also open on https://github.com/apache/incubator-superset/issues/8200
=> [mvc] [pagination] Fix #1127 pagination

examples/masterdetail/app/views.py
Fixed typo to correct name in view
=> Fixes views.py name in view (examples/masterdetail)

docs/rest_api.rst
Small fixes for the REST API docs
=> [docs] Fix, get list result

flask_appbuilder/api/__init__.py, flask_appbuilder/exceptions.py, flask_appbuilder/models/filters.py, flask_appbuilder/tests/test_api.py
=> [api] Fix, don't crash on invalid filters

flask_appbuilder/menu.py
=> [api] [menu] Fix, openapi sec

docs/config.rst, flask_appbuilder/api/__init__.py, flask_appbuilder/tests/test_api.py
New, support for json encoded content on URI parameter
=> [api] New, support for json encoded content on URI parameter

flask_appbuilder/templates/appbuilder/general/lib.html
=> [mvc] Fix: List page's pagination start with 1

docs/security.rst
=> Fix: Sentence incorrectly states the number of authentication methods.

examples/crud_rest_api/app/api.py
an inconsequential change, but also not.
=> Fix: adding nonbinary gender to crud_rest_api/api.py

flask_appbuilder/security/manager.py
=> [security] Fix: Fixed an AttributeError in manager.py when a permission is null.

flask_appbuilder/api/__init__.py
Include HTTP 403 on API default responses
=> [api] New, http 403 forbidden on default responses

flask_appbuilder/security/manager.py, flask_appbuilder/security/sqla/manager.py
@dpgaspar let me know what you think, I was looking for a way to disable this view in Superset
=> [securitymanager] make userstatschartview optional

flask_appbuilder/baseviews.py, flask_appbuilder/tests/test_mvc.py, flask_appbuilder/views.py
Introduces a new MVC attribute to disable the old MVC API flag
=> [mvc] New, disable old API flag and tests

flask_appbuilder/templates/appbuilder/general/lib.html
Fix Jinja2 crash when `ModelView` has defined actions but `action` and/or `action_post` is excluded from registered routes
=> [mvc] Fix, jinja2 crashes with defined actions and removed action routes

CHANGELOG.rst, flask_appbuilder/__init__.py
=> Bump to 2.2.2

flask_appbuilder/security/decorators.py, flask_appbuilder/security/manager.py
Set JWT auth user load to be set on flask `g`
=> [security] Set JWT user on flask g

flask_appbuilder/api/schemas.py, flask_appbuilder/models/sqla/filters.py, flask_appbuilder/tests/test_api.py
API was not accepting lists on filter values for many to many filters
=> [api] Fix, many to many filters

flask_appbuilder/security/decorators.py, flask_appbuilder/security/manager.py
=> Revert "[security] Set JWT user on flask global (#1242)"

flask_appbuilder/security/views.py
=> [security] Fix, Oauth and OID redirect on auth failure

docs/config.rst, flask_appbuilder/security/manager.py, flask_appbuilder/security/sqla/manager.py
=> [auth] introduce optional ci auth

flask_appbuilder/api/__init__.py
Detaching exposed methods logic to <method>_headless makes it easier to override `ModelRestApi`
=> [api] new, make REST API easier to override

flask_appbuilder/security/manager.py
=> [api] Fix, set api jwt user on flask g

requirements.txt
Updating requirements.txt after #1266
=> Fix, update requirements

docs/config.rst, flask_appbuilder/security/manager.py
Make it possible to toggle security views for permissions, view menus and permissions on view menus on and off.
=> [mvc] [security] toggle pvm, perm and vm mvc views config options

CHANGELOG.rst, flask_appbuilder/__init__.py
=> Bump FAB to 2.2.3

docs/actions.rst
=> Fix, typo corrected in doc. Update actions.rst

CHANGELOG.rst
=> [docs] Fix, changelog formatting

flask_appbuilder/views.py
=> [mvc] Fix, use os.path.join for download

docs/actions.rst
=> [docs] Fix, add missing import (doc only)

flask_appbuilder/templates/appbuilder/general/widgets/show.html
=> [mvc] Fix, use formatters_columns with show_fieldsets

rtd_requirements.txt
Fix readthedocs specific requirements, was failing because of the new werkzeug vs flask-babel issue
=> [docs] Fix, read the docs requirements

flask_appbuilder/api/schemas.py, flask_appbuilder/models/filters.py, flask_appbuilder/tests/test_api.py
[api] Fix, list filters validation schema
Closes #1301
=> [api] Fix, list filters validation schema

flask_appbuilder/static/appbuilder/js/ab_actions.js
=> [mvc] Fix, action form submit

requirements.txt, setup.py
Bump prison to address small bug
closes: #1177
https://github.com/betodealmeida/python-rison/pull/4
=> [api] Bump prison to 0.1.3 to address small bug

release.sh
Adds a simple release script to ease pushing to Pypi
=> [deploy] Add release script

CHANGELOG.rst, flask_appbuilder/__init__.py
=> Bump to 2.3.2

flask_appbuilder/menu.py
=> [menu] fix, add translation lookup in menu.get_data

flask_appbuilder/menu.py
=> [menu] Fix, translations on menu v2

docs/i18n.rst
=> New, Added Dutch language to docs

flask_appbuilder/translations/de/LC_MESSAGES/messages.po
Minor fixes for the German translation I noted when using the app.
=> Fix: fixed typos and improved bit of the German translation

flask_appbuilder/security/manager.py
Small doc fix following #1413 sugestion
=> Fix, docs on has_view_access

flask_appbuilder/tests/test_api.py
=> fix: swagger test

rtd_requirements.txt
Doc requirements were out of sync
=> fix, doc dependencies

README.rst
Documents breaking OAuth change on FAB3
=> docs, readme breaking changes for OAuth

flask_appbuilder/security/sqla/manager.py
Fix, query may have multiple results on this case, this may crash del_permission_view_menu
=> fix, del permission assertion on roles

CHANGELOG.rst, flask_appbuilder/__init__.py
New 3.0.1
Improvements and Bug fixes on 3.0.1
- Fix, google charts (#1431)
- Fix, del permission assertion on roles (#1434)
=> release 3.0.1

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.rst
Contributing RST was wrongly written with md
=> docs: fix, contributing

flask_appbuilder/models/base.py, flask_appbuilder/models/sqla/interface.py
Improves and fixes type annotations on SQLAInterface
=> fix: improve type annotations on SQLAlchemy

docs/actions.rst
Simple doc change. Remove possessive in `list's`.
=> Remove incorrect possessive. `list's => lists`.

flask_appbuilder/filemanager.py
Sanitise the uploaded filename on Filemanager
=> fix: sanitise the uploaded filename

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: Bump to 3.1.0

examples/quickhowto3/README.rst, examples/quickhowto3/app/__init__.py, examples/quickhowto3/app/views.py
=> Migrate examples/quickhowto3 to version 3.x.x

examples/quickhowto2/app/static/angularAssets/abModelSearch.html, examples/quickhowto2/app/templates/list_angulajs.html, flask_appbuilder/static/appbuilder/css/ab.css, flask_appbuilder/templates/appbuilder/general/widgets/search.html
This reverts commit c0a15d8177387284f0439ea3f78950bf5024924e.
@ryanahamilton #1491 breaks the search dropdowns because of: https://github.com/dpgaspar/Flask-AppBuilder/blob/master/flask_appbuilder/static/appbuilder/js/ab_filters.js#L140
=> Revert "fix: remove unnecessary classes from dropdowns (#1491)"

README.rst
Add github actions CI badge to README
=> docs: add github actions badge

flask_appbuilder/models/sqla/interface.py
Fix regression caused by #1486 on MVC related order by columns
=> fix: MVC order by on relation

CHANGELOG.rst
change log bullets are missing
=> fix: changelog

docs/security.rst
Improve docs around authentication methods.
=> docs: improve docs around LDAP auth

.github/prlint.json, .github/workflows/ptlint.yml, CHANGELOG.rst, flask_appbuilder/__init__.py
Release 3.2.0
Changelog:
- fix: issue 1469 error in filters (#1541) [Duy Nguyen Hoang]
- fix: showing excluded routes in server log (#1565) [runoutnow]
- refactor: AUTH_LDAP/AUTH_OAUTH + implement role mapping (#1374) [Mathew Wicks]
- fix(api): OpenAPI spec of nested components without auto generated names (#1547) [Daniel Vaz Gaspar]
- fix(mvc): action confirmation on single show view (#1539) [Daniel Vaz Gaspar]
- docs: improve docs around LDAP auth (#1526) [Daniel Vaz Gaspar]
- ci: tests for python 3.8 and 3.9 (#1525) [Daniel Vaz Gaspar]
- docs: fix, swagger path in readme (#1518) [Felix Rilling]
- fix: oauth #1511 (#1522) [Daniel Vaz Gaspar]
- fix: github actions (#1523) [Daniel Vaz Gaspar]
- fix: changelog (#1507) [Daniel Vaz Gaspar]
=> release: 3.2.0

CONTRIBUTING.rst, flask_appbuilder/tests/test_api.py, flask_appbuilder/tests/test_mvc.py, requirements-dev.txt
Give an example on how to run a single test while developing
=> docs: improve contributing run single test

CHANGELOG.rst, flask_appbuilder/__init__.py
Patch release 3.2.1
```
Improvements and Bug fixes on 3.2.1
- docs: improve contributing run single test (#1579) [Daniel Vaz Gaspar]
- fix: sqlalchemy 1.4.0 breaking changes (#1586) [Daniel Vaz Gaspar]
```
=> release: 3.2.1

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.2.2

CHANGELOG.rst, flask_appbuilder/__init__.py
release: 3.2.3
- fix: improve performance for get role permissions (#1624) [Daniel Gaspar]
- feat: get user permissions API (#1620) [Daniel Gaspar]
- fix: Ignore LDAP search referrals (#1602) [Fred Thomsen]
- fix: relax AzureAD mandatory fields (#1608) [hyunjong.lee]
=> release: 3.2.3

docs/templates.rst
This PR regards some typos and small changes to the `docs/templates.rst` file.
* minor typos fixed
* small changes
=> docs: Typos and small changes in docs/templates.rst

docs/i18n.rst
=> docs: fix number of languages in i18n.rst

flask_appbuilder/security/manager.py
=> fix: auth balance

.github/ISSUE_TEMPLATE.md, CONTRIBUTING.rst
Adds a responsible disclosure information.
=> docs: responsible disclosure

CHANGELOG.rst, flask_appbuilder/__init__.py
Release 3.3.0
```
- fix: auth balance (#1634) [Daniel Gaspar]
- feat: Support for conditional menu item rendering (#1631) [Ben Reinhart]
- docs: fix number of languages in i18n.rst (#1630) [Aleksandr Gordienko]
- feat: Add support for before_request hooks (#1629) [Ben Reinhart]
- docs: Typos and small changes in docs/templates.rst (#1625) [Federico Padua]
```
=> release: 3.3.0

flask_appbuilder/security/views.py, flask_appbuilder/utils/base.py
Adds a warning message when creating or editing a user and `AUTH_ROLES_SYNC_AT_LOGIN` is enabled.
cc: @cccs-rc @thesuperzapper
=> fix: add warning text to roles when AUTH_ROLES_SYNC_AT_LOGIN

docs/config.rst, flask_appbuilder/api/manager.py
Allow to use a custom Swagger template through a new config parameter, called `FAB_API_SWAGGER_TEMPLATE`
=> feat: Allow using custom Swagger template for SwaggerView.

requirements.txt, setup.py
Bumping click to 8.0.1 to all us to unblock apache-superset pip-compile updates
=> chore: Bump click to 8.0.1

flask_appbuilder/security/views.py, flask_appbuilder/tests/config_oauth.py, flask_appbuilder/tests/test_mvc_oauth.py, requirements-extra.txt, setup.py
Improves logic on next URL OAuth. Adds type annotations
=> fix: improve next URL on OAuth

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.3.2

rtd_requirements.txt
Fix read the docs requirements
=> docs: fix requirements

.github/workflows/ci.yml, CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.4.0

docs/security.rst
add code example for `AUTH_TYPE=AUTH_OAUTH` for aws-cognito
=> docs: add aws cognito setup code examples

docs/addons.rst, docs/security.rst, docs/user_registration.rst, examples/oauth/app/views.py
Fixes small issues in the documentation such as
1. Changing ``flask_babelpkg`` to ``flask_babel``
2. Fixing typos
=> docs: Fix small documentation issues

flask_appbuilder/security/manager.py, flask_appbuilder/security/mongoengine/manager.py, flask_appbuilder/security/sqla/manager.py
Improves code quality and balances paths
=> chore: improve code quality and balance

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.4.2

flask_appbuilder/security/manager.py
data was not defined which was throwing an error when using azure for oauth.
=> fix: fixing data not defined in azure oauth

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.4.3

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.4.4

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 3.4.5

CHANGELOG.rst, README.rst, docs/breaking.rst, docs/index.rst, flask_appbuilder/__init__.py
=> release: 4.0.0

.github/workflows/ci.yml, docker-compose.yml
Bump postgres to the latest major 14
=> chore: bump postgres to 14

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.1.0

flask_appbuilder/security/views.py
Fix user stats view search, use user list search field list
=> fix: user stats view search

CHANGELOG.rst
Include latest fix on 4.1.3 #1887
=> release: 4.1.3a

flask_appbuilder/security/views.py
Similar to https://github.com/dpgaspar/Flask-AppBuilder/pull/1747 but fixes AuthRemoteUserView
=> chore: Redirect to prev url on login for AuthRemoteUserView

flask_appbuilder/base.py, flask_appbuilder/tests/A_fixture/addon_manager.py, flask_appbuilder/tests/test_addon.py, flask_appbuilder/tests/test_menu.py
Fixes addon manager, adds tests
=> fix: addon managers import

flask_appbuilder/security/utils.py, flask_appbuilder/security/views.py, flask_appbuilder/tests/test_mvc_oauth.py
Fix for: https://github.com/dpgaspar/Flask-AppBuilder/issues/1925
Use a random unique state instead
=> fix: OAuth state parameter

flask_appbuilder/templates/appbuilder/general/security/login_db.html, flask_appbuilder/templates/appbuilder/general/security/login_ldap.html
Fix `label` elements with the wrong `for` attribute.
=> fix: HTML label IDs for DB and LDAP login

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.1.6

flask_appbuilder/api/__init__.py, flask_appbuilder/models/filters.py, requirements-dev.txt
Adds more type annotations to the api module, still a work in progress
=> chore: Add more type annotation to REST API module

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.2.0

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.2.1

CHANGELOG.rst, flask_appbuilder/__init__.py
Bump version and update changelog for 4.3.0
=> release: 4.3.0

flask_appbuilder/translations/ru/LC_MESSAGES/messages.po
Fix for small misspell in russian messages file
=> fix(translations): misspell in ru translations

flask_appbuilder/static/appbuilder/js/ab_filters.js, flask_appbuilder/tests/test_mvc.py
=> fix(mvc): operation filters with new select2

.github/workflows/codeql-analysis.yml
=> ci: add codeQL analysis

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.2

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.4

MANIFEST.in, release.sh
Fixes manifest and uses clean before publishing the pkg
=> fix: release tests exclusion

flask_appbuilder/security/mongoengine/models.py, flask_appbuilder/security/sqla/models.py
Email max length should be 320 = 64 + 1 + 255
=> fix: increase email field length

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.6

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.7

.github/FUNDING.yml
=> docs: add github sponsor

.github/FUNDING.yml
=> fix: add github sponsor

flask_appbuilder/static/appbuilder/css/ab.css, flask_appbuilder/static/appbuilder/js/ab.js, flask_appbuilder/static/appbuilder/js/ab_filters.js
Improve alignment of elements in list filters
Before:
After:
=> fix: filter list UI spacing between elements

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.8

.readthedocs.yaml
=> docs: fix RTD config

.github/SECURITY.md
=> docs: update security policy

README.rst
Forgot to update the readme in #2147 .
=> docs: Update shield of supported Python versions

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.3.10

requirements-extra.txt, rtd_requirements.txt
Bumps several non base dependencies
=> chore: bump several non base dependencies

tests/security/test_auth_oauth.py
Fixes failing test with expired token
=> fix: authentik test

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.4.0

flask_appbuilder/security/views.py
Follow up on https://github.com/dpgaspar/Flask-AppBuilder/pull/2209 add the same search list to User stats view
=> fix: user search list on stats

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.4.1

requirements/base.txt
=> chore: bump werkzeug to 3.0.3

requirements/base.txt
=> chore: bump dnspython to fix vulnerability

docs/customizing.rst
=> docs: Fixing broken link

flask_appbuilder/security/decorators.py, flask_appbuilder/security/views.py, tests/security/test_mvc_security.py
Adds HTTP headers for no cache on login forms
=> feat: add no cache directive to login forms

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.5.1

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.5.2

flask_appbuilder/security/sqla/models.py
Add FK indexes on `ab_permission_view_role` and `ab_permission_view`
On postgres we get more efficient joins by having these
=> chore: improve security models performance

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.5.3

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.5.4

CONTRIBUTING.rst
The path for `requirements*` file are no longer correct. This PR is to update the outdated data.
=> docs: update `requirements` paths in contributing doc

.github/workflows/ci.yml
fix MSSQL CI, error:
```
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08S01', '[08S01] [FreeTDS][SQL Server]Unable to connect: Adaptive Server is unavailable or does not exist (20009) (SQLDriverConnect)')
```
=> ci: fix mssql on CI

flask_appbuilder/security/sqla/apis/role/api.py
Small fix for the OpenAPI spec on update role users:
fixes OAS validation that errors with:
```
Failed validating 'required' in schema['properties']['paths']['patternProperties']['^\\/']['patternProperties']['^(get|put|post|delete|options|head|patch|trace)$']:
{'type': 'object',
'required': ['responses'],
'properties': {'tags': {'type': 'array', 'items': {'type': 'string'}},
'summary': {'type': 'string'},
'description': {'type': 'string'},
'externalDocs': {'$ref': '#/definitions/ExternalDocumentation'},
'operationId': {'type': 'string'},
'parameters': {'type': 'array',
'items': {'oneOf': [{'$ref': '#/definitions/Parameter'},
{'$ref': '#/definitions/Reference'}]},
'uniqueItems': True},
'requestBody': {'oneOf': [{'$ref': '#/definitions/RequestBody'},
{'$ref': '#/definitions/Reference'}]}, …
```
=> fix: openAPI spec for security update role users

flask_appbuilder/security/sqla/apis/role/api.py
Improve role users PUT API performance, fetch all user with a single query
=> fix: improve API for role users update

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.6.1

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.6.2

flask_appbuilder/models/sqla/interface.py
Only add automatic order by primary key on inner queries. This keeps `apply_order_by` backward compatible
=> fix: use id as a tiebreaker in the ordering

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.6.3

flask_appbuilder/security/sqla/apis/user/api.py, tests/test_security_api.py
Fixed the bug where you would a update a user and the password would get changed automatically.
=> fix(UserApi): Fixed pre_update issue

flask_appbuilder/api/__init__.py, flask_appbuilder/security/sqla/apis/__init__.py, flask_appbuilder/security/sqla/apis/group/__init__.py, flask_appbuilder/security/sqla/apis/group/api.py, flask_appbuilder/security/sqla/apis/group/schema.py, flask_appbuilder/security/sqla/apis/role/api.py, flask_appbuilder/security/sqla/apis/role/schema.py, flask_appbuilder/security/sqla/apis/user/api.py, flask_appbuilder/security/sqla/apis/user/schema.py, flask_appbuilder/security/sqla/manager.py, tests/test_security_api.py
This PR introduces a new GroupAPI to Flask App Builder and enhances the existing UserAPI and RoleAPI by integrating group-related functionalities.
➕ Added: GroupAPI to manage user groups within FAB
🔄 Updated: UserAPI and RoleAPI to include group relationships, allowing better integration and visibility of user-group-role associations
- This improvement aims to:
- Provide a dedicated API endpoint for managing groups
- Allow users and roles to reflect group relationships via their respective APIs
Set the foundation for more granular access control and user management in future features
=> feat(GroupAPI): Add GroupAPI to FAB

CHANGELOG.rst, flask_appbuilder/__init__.py
=> release: 4.8.1
