dpgaspar/Flask-AppBuilder

- bin/migrate_db_1.3.py
- docs/versionmigration.rst
I need (well, want) to use FAB's ability to add a table rather than writing raw SQL code since that code depends on the db type. I was able to run db.create_all() but in order to get that it work right, I had to manually type in  the SQLALCHEMY_DATABASE_URI since the config read had issues with paths. Maybe you can take a look as it would be nice to just run
```
python /path/to/bin/migrate-db_1.3.py
```
Tested with sqlite. Needs testing on mysql and postgresql.
Also I left a lot of the structure  / functions from the older 0.7 migration script. Maybe they will be useful in later migration scripts. I could remove them. Thoughts?
Also, I'm not deleting the role_id column on the user table as I think you mentioned wanting to keep it even though it isn't being used for compatibility reasons. …
> First pass at migration script

- flask_appbuilder/security/sqla/registerviews.py
I made two small change since it failed to render the activation template since base_template was undefined, works fine now, I also changed it for the rendering of the email template, although this didn't make any problems, but this way it is always the same rendering function.
The second change in the same file is from get_role_by_name to find_role, since get_role_by_name does not exist anymore 
greets martin
> replaced render_template with self.render_template

- flask_appbuilder/models/generic/__init__.py
- flask_appbuilder/models/generic/filters.py
hi,
due to my needs I've derived a series of generic* classes into my project and I've implemented additional filters for the generic interface. I don't know if this can help the project in anyway.
The expected behaviour is to have out-of-the-box filters for equal, greater, smaller, like, insensitive like, starts with and so on...
In order to make pull request a bit more streamlined, I've merged the contents of my custom classes into the FAB's base classes I've derived from.
The merged code needs *a lot* of debugging as I've merged it very fast in order to avoid to put a lot of crap into my custom classes making future merges impossible.
hope this helps.
bye,
MN
> added a number of new filters for the generic interface, plus a fix to the 'like' and 'equal' operators

- flask_appbuilder/views.py
We have somewhat of an unusual setup in our intranet where we use a reverse proxy that provides SSL and LDAP authentication and routes the request to application while adding headers we use to authenticate.
I was getting the message bellow in Chrome, and the inline CRUD widgets didn't work properly behind the proxy, so I tracked it down to these 2 lines of code, and found an easy alternative in the Flask request object in the form of `full_path`.
For reference here's the difference between `url` and `full_path`
```
>>> request.url
https://github.com/dpgaspar/Flask-AppBuilder
>>> request.full_path
/github.com/dpgaspar/Flask-AppBuilder
```
Chrome message:
```
Mixed Content: The page at 'https://panoramix.d.musta.ch/datasourcemodelview/edit/50' was loaded over a secure connection, but …
```
> Fixing 'Mixed Content' message when behind an https reverse proxy

- flask_appbuilder/models/mongoengine/interface.py
- Greatly improved overall speed
- len(objs) previously retrieved all objects. The recommended approach is
objs.count(). Greatly reduces overhead.
- Added some error checking and a simple warning if lots of data is being
downloaded
- Fixed error: if page given but not page_size, None error when multiplying,
line 47 (old version)
- Made it slightly more pythonic
> Made several changes to query method:

- setup.py
Here's the commit that changes the `current_user.is_authenticated` and pretty much all `is_.*` calls...
https://github.com/maxcountryman/flask-login/commit/7b2583c45ac383029605adf4f9f4a7f23161f782#commitcomment-13199701
This was apparent to me when users aren't logged in in flask appbuilder and AnonymousUserMixin is the generic user used at that moment.
> Pinning Flask-Login to 0.2.11 since 0.3.0 breaks the common interface

- flask_appbuilder/models/generic/__init__.py
- flask_appbuilder/models/generic/filters.py
now the generic model/session is able to cope with datetime.date objects. While the _equal operator has only been tested filling generic models with dates coming from a sqlite db, it seems that SQLAlchemy makes a good effort in standardiziing the format of the date objects output, so generic models should be OK with other backends.
*ANYWAY* proper test with other db is suggested. feel free to drop this pull if you can't trust it: In the end I've not figured out how to test unit the thing!
> added datetime.date objects to generic models

- flask_appbuilder/security/manager.py
Without `AUTH_USER_REGISTRATION` set to `False`, ldap users logging in for the first time are bound successfully, but an account is never made for them (See #314).
Enabling `AUTH_USER_REGISTRATION`, however sees the `SecurityManager` attempting to load a view that will never come. This change loads the view only when there is one to be had.
> Fixes #273 by not registering a view that will not exist for LDAP

- flask_appbuilder/templates/appbuilder/general/widgets/form.html
I noticed there was this blank space at top of forms and finally got to
tracking down its provenance. The missing `<td>` tags in tables somehow made some `<div>`
tags to bubble out of the table. This PR addresses it.
Before / After
> Fixing the blank space at the top of forms

- flask_appbuilder/templates/appbuilder/general/widgets/form.html
Reverts dpgaspar/Flask-AppBuilder#324
Nop, the problem is on lib.render_field it will render the div for each field. I'll fix it.
Thanks for reporting this one.
> Revert "Fixing the blank space at the top of forms"

- flask_appbuilder/babel/manager.py
- flask_appbuilder/babel/views.py
- flask_appbuilder/base.py
- flask_appbuilder/charts/views.py
- flask_appbuilder/charts/widgets.py
- flask_appbuilder/fieldwidgets.py
- flask_appbuilder/messages.py
- flask_appbuilder/security/registerviews.py
- flask_appbuilder/tests/test_base.py
- flask_appbuilder/upload.py
From: http://flask.pocoo.org/docs/0.11/extensiondev/#extension-import-transition
```
As of Flask 0.11, most Flask extensions have transitioned to the new
naming schema. The flask.ext.foo compatibility alias is still in Flask
0.11 but is now deprecated – you should use flask_foo.
```
> Realign deprecated references to `flask.ext`

- bin/hash_db_password.py
- bin/migrate_db_1.3.py
- examples/quickhowto/app/views.py
- examples/quickhowto3/app/__init__.py
- flask_appbuilder/models/sqla/__init__.py
- setup.py
This replaced all occurencies of flask.ext.something with flask_something to avoid the deprecation warning in Flask 0.11
http://flask.pocoo.org/docs/0.11/extensiondev/#extension-import-transition
> Flask extension proper import

- flask_appbuilder/forms.py
- setup.py
I've been seeing the message: 
```
FlaskWTFDeprecationWarning:
"flask_wtf.Form" has been renamed to "FlaskForm" and will be removed in
1.0.
```
in my builds and this should tackle it. Also bumping the setup.py to
`>0.12` as I'm running that version without any issues.
Message can be observed in this build:
https://travis-ci.org/airbnb/caravel/jobs/172202030
> flask_wtf.Form has been renamed to FlaskForm

- flask_appbuilder/security/views.py
Don't reference userinfo if it has not been set.
Refs #396
> securty: don't crash on oauth errors

- flask_appbuilder/templates/appbuilder/general/lib.html
Hi,
I would like to propose this change to the default page sizes for lists, which currently has too many little increments and a low maximum value:
- 5
- 10
- 15
- 20
- 25
- 30
- 35
Which leads users to always select 35 and still leaves them with high page counts if a view has a few hundreds items.
With the proposed change, the list will have less items with bigger increments:
- 25
- 50
- 75
- 100
> More sensible default page size

- .travis.yml
- flask_appbuilder/templates/appbuilder/navbar.html
this will prevent images to flood out of navbar estate.
I've recently added an icon for the app and the image has been rendered in its full size, going out of the navbar. this should fix the thing.
While I do not expect that _height="100%" width="auto"_ will be the one-fit-for-all, at least the default is now more sane IMHO.
User can override the template and customize it anyway.
> added default autosizing to app image (if any)

- .travis.yml
- flask_appbuilder/baseviews.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/templates/appbuilder/general/model/list.html
- flask_appbuilder/templates/appbuilder/general/widgets/list.html
- flask_appbuilder/templates/appbuilder/general/widgets/show.html
- flask_appbuilder/tests/test_base.py
Dictionary of formatter callables used to format columns in list and show widgets. This allows user to apply whatever formatting they want to their data. Similar to:
http://flask-admin.readthedocs.io/en/latest/api/mod_model/#flask_admin.model.BaseModelView.column_formatters
For context, I'm currently attempting to port the [Apache Airflow](https://github.com/apache/incubator-airflow) UI from `Flask-Admin` to FAB and may need to match some of the functionality there. The incentive is getting auth, and REST for all of our model from FAB while having a easy-ish port from Flask/ Flask-Admin
> Adding column_formatters to ModelView

- flask_appbuilder/base.py
- flask_appbuilder/security/sqla/manager.py
Many unexpected errors are silenced in a way that is hard to track down. Adding some `logging.exception(e)` in base.py will help make errors be more verbose and provide a way to track them down.
I went down the rabbit hole when a perm on a new view was not getting created as it should. Adding a simple condition helped moving forward, though I'm guessing the root cause is at least one degree removed.
> Log stack trace on error and prevent view menu creation bug

- flask_appbuilder/security/views.py
When CSRF_ENABLED (WTF_CSRF_ENABLED), there is error with User object don't have csrf_token.
This fixes https://github.com/airbnb/superset/issues/2232 for me, 
because csrf_token is overwritten to None.
Also, there is some deprecation warnings that already fixed on master, can we get minor version bump soon?
> fix: dont overwrite csrf_token on form fill

- flask_appbuilder/security/views.py
- flask_appbuilder/tests/test_base.py
- flask_appbuilder/views.py
This PR fixes two parts of flask-appbuilder that doesn't work when running a site under a prefix.
The most important one is in the CompactCRUDMixin used for inline add/edit views for a ModelView. The session parameter that is used to set the form action only used `request.full_path`. This will not work when the wsgi `SCRIPT_NAME` is different than `''`. Adding in the `request.script_root` solves this problem.
The second one is that the DBAuthView redirects to `/` rather than `self.appbuilder.get_url_for_index`. This will also break on a flask app build that uses a different url for it's index page than `/`
> Fix two instances of urls being generated wrongly when running under a prefix.

- flask_appbuilder/static/appbuilder/css/ab.css
> [cosmetic] left-align the text in filter dropdown

- flask_appbuilder/static/appbuilder/css/ab.css
- flask_appbuilder/templates/appbuilder/general/lib.html
I thought this make a lot of primary buttons on one page, making them
default allows to better highlight the [+] button
Feel free to pass on this PR if you prefer the current settings
> [cosmetics] making row button (show/edit/delete) not primary

- docs/security.rst
Why would you like to import `AUTH_OAUTH` twice?
> Fix docs, remove duplicate import.

- docs/fabmanager.rst
- flask_appbuilder/console.py
support `-k gettext` parameter when extract translatable strings using `fabmanager babel-extract`.
> fix babel-extract command

- flask_appbuilder/fields.py
- flask_appbuilder/forms.py
- flask_appbuilder/models/base.py
- flask_appbuilder/models/generic/filters.py
- flask_appbuilder/models/sqla/filters.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_base.py
This is an attempt to support Sqlalchemy Enum types. I don't use Mongo so I'm not sure if there is an equivalent type there. Should resolve #408, I guess.
I also used destructuring-bind for a loop over conversion_table to increase readability.
(tested with Python 3.4)
> support for Enum type (sqla only)

- flask_appbuilder/views.py
It will raise "AttributeError: 'NoneType' object has no attribute 'id' ", when session_form_edit_pk doesn't exist in database.
> check whether `session_form_edit_pk` still exist in db

- flask_appbuilder/baseviews.py
I am not sure if this is the right place to address this issue but it worked for me...
The problem is that if one has two related models and wants to disable changing relationship then editing via related view raises "AttributeError: 'DynamicForm' object has no attribute ...".
An example:
```
class X(Model):
id = Column(Integer, primary_key=True)
name = Column(String, nullable=False)
note = Column(String)
def __repr__(self): return self.name
class Y(Model):
id = Column(Integer, primary_key=True)
name = Column(String, nullable=False)
note = Column(String)
x_id = Column(Integer, ForeignKey(X.id), nullable=False)
x = relationship(X)
def __repr__(self): return self.name
```
```
from .models import X, Y
class YView(ModelView):
datamodel = SQLAInterface(Y)
add_columns = ['x', 'name', 'note'] …
```
> fix for AttributeError when edit_columns on a view in related_views does not include relationship

- docs/views.rst
The name of the sample of `Form Views` shoule be `SimpleForm` not `SimpleView2`.
> fix typo in views.rst

- flask_appbuilder/base.py
Whenever we re-deploy Superset at Airbnb, we restart 5 web servers which
all have a set of many Gunicorn workers.
Each one of these workers is a process and inits the FAB app, resulting
in a fair amount of database contention around perms tables, and sometimes ultimately
leading to bad database state as I suspect that the perms merge
operations aren't well transaction-insulated. We've added unique
constraints on the DB preventing that, but that's not a great solution.
This PR adds a flag to AppBuilder allowing to turn off perm updates on
init.
The default behavior stays unchanged though.
Note that I decided to add the condition inside `_add_menu_permissions` and `_add_permissions` as opposed to adding them in the calling methods since they `_add_permissions` is called multiple times and …
> Make updating perms on init optional

- flask_appbuilder/baseviews.py
This is a feature currently in flask_admin that I find to be pretty useful.
When an edit view is rendered, sometimes we want to preprocess/prefill the form when we have extra fields available that are not part of the model but depends on the data in the model. This makes it possible to render the processed edit view.
> Add feature to allow form prefill

- flask_appbuilder/baseviews.py
This allows the form to be processed upon submission. 
Useful if there are extra fields submitted that are not part of the data model attributes, and need to be processed prior to populating the data model.
cc  @mistercrunch
> Add feature to allow form to be processed prior to populating model

- flask_appbuilder/security/manager.py
I'm using AUTH_REMOTE_USER with LDAP auth done by an HTTP reverse proxy.  The [docs say](http://flask-appbuilder.readthedocs.io/en/latest/security.html#authentication-methods):
> Finally you can allow users to self register...These settings can apply to all the authentication methods
which is not true.  This patch makes it true for AUTH_REMOTE_USER.
> Support AUTH_USER_REGISTRATION with AUTH_REMOTE_USER

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_sqlalchemy.py
This will allow any [custom sa types](http://docs.sqlalchemy.org/en/latest/core/custom_types.html) (e.g. UtcDateTime in Airflow) inherited from TypeDecorator class. 
cc @mistercrunch
> Accept SQLAlchemy custom types defined by TypeDecorator

- flask_appbuilder/baseviews.py
- flask_appbuilder/models/sqla/filters.py
- setup.py
datetime.strptime doesn't handle the parsing of timezone-aware dates very well; plus this is easier to read.
> Use `dateutil.parser.parse` method instead of `strptime` 

- docs/fabmanager.rst
- flask_appbuilder/console.py
- flask_appbuilder/tests/test_fabmanager.py
It is convenient to have a scriptable method for creating users.  It might be cleaner to merge this with 'create-admin', but I don't see an easy way to do that without either changing the name of 'create-admin', or having usage 'fabmanager create-admin --role=non-admin role', which just seems wrong.
> Implement create-user command to fabmanager

- flask_appbuilder/models/sqla/__init__.py
The Model is already decorated with @as_declarative, so when SQLA wraps that again in a call to declarative_base(), it's creating yet another instance of declarative_base. This is causing flask_migrate (which uses SQLA.Model.metadata) to not recognize all the tables I've declared when I subclass from Model (since the metadata instances are different).
> Remove double-instantiation of declarative base

- flask_appbuilder/templates/appbuilder/general/widgets/base_list.html
- flask_appbuilder/templates/appbuilder/general/widgets/group_form_list.html
It appears that since
https://github.com/dpgaspar/Flask-AppBuilder/pull/797 , there have been
issues rendering inlines that show as HTML.
This quick fix addresses it, and a quick test shows that <script> tags
get rendered as strings so things are still secure following this fix.
> Fix list and form widget rendering html InLine

- flask_appbuilder/baseviews.py
Fixes issue #838. Change the log statement to get the actual name of the view through getting the class `.__name__`  attribute instead of `.name`
> Fix issue 838: Views has no attribute name error raised in log statement

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_sqlalchemy.py
The SQLAInterface.is_relation_one_to_one only returned true for one end of a one-to-one relation, not for the other end. This is because sqlalchemy reports the relation with direction=ONETOMANY or direction=MANYTOONE (depending on the side of the relation). The previous code only checked the ONETOMANY side, not the MANYTOONE. This is now fixed (including a test).
> Fix: Only one end of the one-to-one relation returned the right result

- flask_appbuilder/console.py
The problem is that when appbuilder is in a different module,  one needs to use `fabmanager --appbuilder` to specify the variable,  however the import_application code does not use the appbuilder variable.  Instead it uses the string literal "appbuilder".  I believe this is a typo.
fixes  #861
> Fix, Console: Use appbuilder variable instead of literal.

- flask_appbuilder/baseviews.py
- flask_appbuilder/templates/appbuilder/general/model/edit.html
- flask_appbuilder/templates/appbuilder/general/model/edit_cascade.html
- flask_appbuilder/templates/appbuilder/general/model/show.html
- flask_appbuilder/templates/appbuilder/general/model/show_cascade.html
- flask_appbuilder/templates/appbuilder/general/security/login_db.html
- flask_appbuilder/templates/appbuilder/general/security/login_ldap.html
- flask_appbuilder/templates/appbuilder/general/security/login_oid.html
- flask_appbuilder/templates/appbuilder/general/widgets/form.html
- flask_appbuilder/templates/appbuilder/general/widgets/form_horizontal.html
- flask_appbuilder/templates/appbuilder/general/widgets/form_inline.html
- flask_appbuilder/templates/appbuilder/general/widgets/form_vertical.html
- flask_appbuilder/tests/test_base.py
- flask_appbuilder/tests/test_ldapsearch.py
- flask_appbuilder/tests/test_mongoengine.py
So that apps using appbuilder can configure jinja to error on undefined variables, explicitly test whether template variable are defined rather than treating undefined as falsy.
> Support jinja2 StrictUndefined.

- docs/config.rst
This just adds a description to the documentation for the optional LDAP configuration field `AUTH_LDAP_SEARCH_FILTER`. I noticed in the code this was available but not mentioned in the documentation.
This is my first pull request on an open-source repo, so apologies if I haven't followed protocol -- I appreciate any help or suggestions.
> Add documentation for AUTH_LDAP_SEARCH_FILTER

- flask_appbuilder/security/decorators.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/security/views.py
- flask_appbuilder/templates/appbuilder/general/security/login_oauth.html
- rtd_requirements.txt
- setup.py
Currently, after a user goes through the authentication flow they are sent to the index page, instead of the page they tried to visit initially.
I improved the flow by storing the initial URL in a `state` parameter, that is signed and sent to the OAuth provider [[see docs](https://auth0.com/docs/protocols/oauth2/oauth-state)]. One the user has been authenticated, the `state` parameter received back from the provider is used to redirect them to the initial URL.
Note that the `state` is signed, to avoid a malicious provider of redirecting the user to a URL they control.
I tested the workflow with Superset, and it works as expected. I only tested with Google OAuth.
> Feature: redirect after login/register with OAuth

- docs/rest_api.rst
- flask_appbuilder/api/convert.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/sqla/models.py
- flask_appbuilder/tests/test_api.py
Fixes #947
- M-M fields will default to not required
- Possible to add on the info dictionary a required flag
``` python
tags = relationship("Tag", secondary=assoc_contact_tag, backref="contact", info={'required': True})
```
> [api] Fix, M-M fields are always required, now default to not required #947

- flask_appbuilder/security/mongoengine/manager.py
- flask_appbuilder/security/sqla/manager.py
[security] Fix, find permission view menu superset #1944
Checks if permission or view_menu exists before the query
> [security] Fix, find permission view menu superset #1944

- flask_appbuilder/security/manager.py
The ab_user SQL table may have a unique constraint for the
'email' attribute, leading to failures while inserting data
for a new user registration. Changing the default to a
unique value should fix the problem.
Issue: #965
> Fix: change the default email value for auth_remote_user in security manager

- docs/rest_api.rst
The first REST API doesn't work if @expose decorator is missed.
So add it back into this doc, and it won't make readers like me confused.
For Fixes:
> [docs] Fix, lack of @expose decorator in rest api example

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Version 2.1.0:
- New, #977 flask-sqlalchemy bump to 2.4.0 (new config options)
- New, #986 Builtin roles using regex, Admin role is now one of these
- New, #969 Override class and method permission names and procedure to converge/migrate
- Fix, #985 Deprecation warning EOL version was wrong
- New, #976 pRison version bump
- Fix, #966 Change the default email value for auth_remote_user in security manager
> New, version 2.1.0

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New 2.1.1
- Fix, #991 Make Admin builtin optional, only if declared on config
> Bump FAB to 2.1.1

- flask_appbuilder/security/manager.py
If it still exists on the DB a role with the same name has the
builtin role, permission can be granted is the DB permissions
are wider then the permissions of the builtin
> [security] hotfix, if builtin role don't check db also

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New 2.1.1
- Fix, #993 App factory pattern, AppBuilder object can be fully configured using config keys
- Fix, #994 If builtin role don't check db also, higher permission on DB would allow access
> New, version 2.1.2

- docs/templates.rst
The docs for overwriting the show template say `edit` instead of `show`.
For Fixes:
> Fix, docs for overwriting show template is wrong

- flask_appbuilder/api/__init__.py
Fixes Swagger UI default route, impose lower case on OpenApi spec.
> [api] Fix, default resource name must be lower case

- flask_appbuilder/api/__init__.py
- flask_appbuilder/tests/base.py
- flask_appbuilder/tests/test_api.py
This addresses #1011 
All API's are CSRF exempt if csrf if registered has a Flask extension
> [api] Fix, make all API CSRF exempt by default if csrf exists

- flask_appbuilder/api/convert.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/sqla/models.py
- flask_appbuilder/tests/test_api.py
Support for custom property fields on ``ModelRestApi``
support SQLA Model fields like:
```
class SomeModel(Model):
....
@property
def some_property(self):
return "some"
> [api] New, support custom property fields

- flask_appbuilder/models/sqla/interface.py
- requirements.txt
- setup.py
Fixes #1009.
I need to add a `sqlalchemy_utils.types.uuid.UUIDType` field to Superset and have it work with `Flask-AppBuilder`. We are adding a uuid field to `superset.models.helpers.ImportMixin` to help import/export unique assets without the IDs clobbering one another or getting confused.
```python
class ImportMixin(object):
export_parent = None
export_children = []
export_fields = []
uuid = sa.Column(UUIDType(binary=False), unique=True, default=uuid.uuid4) 
...
class Slice(Model, AuditMixinNullable, ImportMixin):
"""A slice is essentially a report or a view on data"""
```
At the moment errors are thrown because the uuid field does not return is_string (it is a CHAR(32) unless a UUID type is present), as it does not turn up in models.sqla.interface._is_sqla_type. A 'Column uuid Type not …
> New: Adds sqlalchemy_utils.types.uuid.UUIDType support to String fields

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/sqla/models.py
- flask_appbuilder/tests/test_api.py
On `ModelRestApi` using dotted notation for two relation to the same model raises exception: AmbiguousForeignKeysError
Fixes #1026
> [api] Fix, api dotted notation joins to same table

- docs/views.rst
The last example in **BaseViews** documentation uses the `flash` function from flask, but the import was missing.
> Fix, missing import in views example

- flask_appbuilder/filters.py
If role still contains a permission that is missing on `BaseView` or `BaseApi` `base_permissions` override, `is_item_visible` returns True. This behavior may be confusing and saves a round trip to the DB.
> [security] Fix, is item visible returns true is perm exists on role

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New version 2.1.5
- New, #1040, #1041 Bump prison to 0.1.2 and remove requests dependency
- Fix, #1042 is_item_visible confusing behaviour with base_permissions when perm is still on DB
> New version 2.1.5

- flask_appbuilder/security/manager.py
Found this easy minor perf improvement while digging around finding
solutions for #1039
Related thoughts:
* my intuition is that the best/easiest optmization would be to simply
run a single query joining user, roles and perms checking for that
single
permission very quickly. The only downside of that is if `user.roles` is
getting iterated over later in the request cycle, you have to pay the
cost of loading it anyways. Maybe `_has_view_access` could have
different mode of operations where it tries to fetch and cache things
as opposed to the single check against the db.
* noticed `re.match` being used potentially a lot for static roles, we
may want to re.compile and cache. This may be a premature
optimization though, unclear...
related to: …
> perf: improve perf while checking perms

- flask_appbuilder/security/manager.py
- flask_appbuilder/security/mongoengine/manager.py
- flask_appbuilder/security/sqla/manager.py
- flask_appbuilder/security/sqla/models.py
WiP
Following reported problem on #1039 
Log from SQLAlchemy echo:
```
2019-06-24 14:36:36,347 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2019-06-24 14:36:36,349 INFO sqlalchemy.engine.base.Engine SELECT ab_user.id AS ab_user_id, ab_user.first_name AS ab_user_first_name, ab_user.last_name AS ab_user_last_name, ab_user.username AS ab_user_username, ab_user.password AS ab_user_password, ab_user.active AS ab_user_active, ab_user.email AS ab_user_email, ab_user.last_login AS ab_user_last_login, ab_user.login_count AS ab_user_login_count, ab_user.fail_login_count AS ab_user_fail_login_count, ab_user.created_on AS ab_user_created_on, ab_user.changed_on AS ab_user_changed_on, ab_user.created_by_fk AS ab_user_created_by_fk, ab_user.changed_by_fk AS ab_user_changed_by_fk 
FROM ab_user …
```
> Fix performance issues on permission checks

- flask_appbuilder/security/api.py
Fixes #1047 
Add a second JWT security schema for the refresh token. This adds a second input for the refresh token to the auth form in the interactive swagger docs.
Set the security schema on the refresh operation to the refresh token schema. This adds a lock icon to the refresh operation and automatically includes the refresh token in the header of refresh requests.
---
This allows the refresh API to be tested through the swagger docs and documents how the refresh API should be used.
> [openapi] Fix, require refresh security token

- flask_appbuilder/baseviews.py
Related to https://github.com/apache/incubator-superset/pull/5449 which uses SQLAlchemy listeners for pre-insert and pre-update validation (this is required as Superset also contains a React component for editing models), this PR catches potential exceptions which may be thrown by the listener when WTForms attempts to populating the object.
to: @dpgaspar @mistercrunch
> Fix, Catch exception with populating form

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New 2.1.6
Improvements and Bug fixes on 2.1.6
- Fix, #1050 Catch exceptions on populating forms
- Fix, #1046 API include openapi security spec on paths
- Fix, #1048 API include refresh token on openapi security specs
- Fix, #1045, #1044 Performance improvement on permission checks
> Bump to 2.1.6

- flask_appbuilder/api/__init__.py
- tox.ini
`label_columns` were not being returned properly by the API when we override `list_columns` also.
example:
```
class ContactModelApi(ModelRestApi):
resource_name = "contact"
datamodel = SQLAInterface(Contact)
allow_browser_login = True
list_columns = ["name", "address", 'birthday', 'contact_group.name']
```
> [api] Fix, label_columns with list_columns override

- flask_appbuilder/__init__.py
- flask_appbuilder/api/__init__.py
- flask_appbuilder/base.py
- flask_appbuilder/tests/test_api.py
- setup.py
Introduces a class property `max_page_size` to override global setting FAB_API_MAX_SIZE
``` python
class TestApi(ModelRestApi):
datamodel = SQLAInterface(Model1)
max_page_size = -1
class TestApi(ModelRestApi):
datamodel = SQLAInterface(Model1)
max_page_size = 200
```
> [api] New, max_page_size class property override for FAB_API_MAX_SIZE

- flask_appbuilder/api/__init__.py
`ModelRestApi` info endpoint was not translating labels and descriptions
> [api] Fix, info not translating labels and description

- CHANGELOG.rst
- RELEASE.rst
- flask_appbuilder/__init__.py
- flask_appbuilder/api/__init__.py
New release 2.1.8
- Fix, #1077 API Info not translating labels and description
- Fix, #1069 API label_columns for get item returning labels for list columns
- Fix, #1072 API max_page_size class property override for FAB_API_MAX_SIZE
> Bump to 2.1.8, new RELEASE doc

- flask_appbuilder/api/__init__.py
`max_page_size` when using special `-1` value to unlimit results issues queries with LIMIT -1, that result in error
> [api] Fix, negative page size issues SQL with negative LIMIT

- flask_appbuilder/__init__.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/base.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/tests/test_api.py
FAB_ADD_SECURITY_VIEWS=False will not include any security view, give devs
the chance to override `register_views` and add their custom views
instead
> [security] Fix, make possible to override when using FAB_ADD_SECURITY_VIEWS

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New 2.1.10
- Fix, #1079 Make it possible to override register_views when using FAB_ADD_SECURITY_VIEWS
> Bump FAB to 2.1.10

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New FAB 2.1.12
Improvements and Bug fixes on 2.1.12
------------------------------------
- Fix, #1096 Bootstrap and Bootswatch bump to 3.4.1
- Fix, #1097 python version restriction on setup > 3.6 < 4
- Fix, #1095 OAuth set fallback when next url in state is empty
Related issues: #1093
> New FAB 2.1.12

- flask_appbuilder/security/manager.py
@AlexisLessard Please try to apply these changes and let me know if you still see the issue. I do not have access to an LDAP server to test with at the moment.
Closes #1118
> Fix, ldap: safely retrieve error object attribute

- flask_appbuilder/templates/appbuilder/general/security/login_db.html
- flask_appbuilder/templates/appbuilder/general/security/login_ldap.html
- flask_appbuilder/templates/appbuilder/general/security/login_oid.html
Improvement, Add autofocus attribute to login page.
related issue: https://github.com/dpgaspar/Flask-AppBuilder/issues/1131
> Add autofocus attribute to login page.

- flask_appbuilder/base.py
- flask_appbuilder/menu.py
- flask_appbuilder/tests/test_api.py
- flask_appbuilder/tests/test_menu.py
- flask_appbuilder/tests/test_mongoengine.py
- flask_appbuilder/tests/test_mvc.py
exposes a method on the menu class to output the menu as list of dictionaries that can be converted to json.
> New: expose menu data as serializable objects

- flask_appbuilder/babel/manager.py
- flask_appbuilder/templates/appbuilder/navbar_right.html
- flask_appbuilder/tests/test_api.py
- flask_appbuilder/tests/test_mvc.py
Fixed:
- Empty LANGUAGES definition crash
- Remove drop down language selection if LANGUAGES is empty or just one
- Fix API requesting a non existing language crash
> [babel] Fix, crash with empty LANGUAGES config key

- flask_appbuilder/security/api.py
When calling the JWT refresh endpoint (/security/refresh) using the refresh_token it should return a new access_token
But it's returning a new refresh_token
However looking at the FAB source code I think it is indeed returning a new access_token but naming it as refresh_token
> Fix, JWT refresh endpoint should return new access_token

- flask_appbuilder/models/filters.py
Without this change, filters for e.g. add endpoints on views will not
be created unless there are search_columns defined.
This leads to a KeyError when filter columns are indexed,
breaking endpoints like /fooview/add?_flt_0_bar=1 even when
bar is a column that can be filtered.
> Fix, create filters even when search_columns is empty

- flask_appbuilder/security/manager.py
This aids in security-related log analysis, because the failure and
reason for failure are clearly encapsulated into a single log line.
> [security] New, state reason for LDAP login failure

- docs/templates.rst
- flask_appbuilder/templates/appbuilder/general/widgets/show.html
With the help of these blocks it is now possible to override parts
of the show template.
For example it is now possible to create a custom template that extends
the default show.html widget template to add a second set of action
buttons to the top of the show widget area. This makes it easier to
reach the actions in case the page is longer.
Imho the actions should be on top by default for usability reasons, but did
not want to propose such a change for the project. The blocks should
generally make it more flexible.
> New, Show widget template: Add some basic blocks

- flask_appbuilder/api/schemas.py
Adds a missing key (edit_columns) on the OpenApi spec for the `_info` endpoint
> [api] Fix, openapi spec for the info endpoint

- flask_appbuilder/security/sqla/manager.py
This commit applies for oralce dialect the same query strategy already implemeted for MSSQL in
security manager when checking for authentication/permissions, since a
query like "SELECT EXISTS(1) FROM DUAL" in oracle databases would raise
an ORA-00936: missing expression error (observed from version 18c on)
Steps to reproduce the error:
1 - Configure a connection through the oracle dialect to an oracle instance (>=18c)
2 - Create an admin user through flask fab create-admin
3 - Login into the application
For Fixes:
Please, prefix the title with "New, " and describe this new feature in detail, …
> [security] Fix, authentication error when using oracle dialect

- setup.py
marshmallow-sqlalchemy 0.19.0 is incompatible with py2 and py3.5 (syntax errors); Flask-AppBuilder's dependency on marshmallow-sqlalchemy breaks downstream projects on py2 and py3.5, including Apache Airflow.
This change repins the dependency in setup.py to `marshmallow-sqlalchemy>=0.16.1, <0.19.0` instead of `marshmallow-sqlalchemy>=0.16.1, <1`. (cf. the requirements.txt pin to `marshmallow-sqlalchemy==0.16.2`.
> Fix: marshmallow-sqlalchemy update breaks py2 and 3.5 compatibility

- docs/rest_api.rst
- flask_appbuilder/api/__init__.py
- flask_appbuilder/tests/test_api.py
New, BaseApi property to exclude route methods:
`exclude_route_methods`: Will not register the route on the blueprint and will not create a permission for it
> [api] New, exclude route methods from ModelRestApi

- flask_appbuilder/models/sqla/interface.py
Fix, don't exclude boolean from get_search_columns_list
> [api] Fix, re-allow filtering by booleans (default generated list)

- flask_appbuilder/baseviews.py
Default page size should match the minimal step defined on the
MVC macro, the user was not getting info about the size of the page
> [mvc] Fix, default page size

- flask_appbuilder/api/__init__.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/tests/test_mongoengine.py
Fixes:
- OpenAPi route exclusion when swagger is disabled
- Don't register openapi spec on excluded methods
- Allow for non marshmallow-sqlalchemy declarations (support schemas without unique)
> [api] Fix, OpenAPI method and config exclusions

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Improvements and Bug fixes on 2.2.1
- Fix, [api] OpenAPI method and config exclusions (#1211)
- Fix, [mvc] default page size out of sync with jinja macro (#1209)
- New, [api] Support for json encoded content on URI parameter (#1205)
- Fix, [api] Re-allow filtering by booleans (default generated list) (#1204)
- Fix, [api] [menu] openapi spec (#1203)
- New, [api] Exclude route methods from ModelRestApi (#1202)
- Fix, [api] Don't crash on invalid filters (#1200)
- Fix, authentication error when using oracle (#1193)
- Fix, [api] openapi spec for the info endpoint (#1197)
- Fix, New, Show widget template: Add some basic blocks (#1158)
- New, State reason for LDAP login failure (#1164)
- Fix, [docs] Get list result (#1196)
- Fix, [examples] Update views.py …
> Bump FAB to 2.2.1

- CHANGELOG.rst
The requirement is explicitly added in 2.1.12, but `f"${strings}"` have been
in use since e0f0e06
> Note that 2.0.0 requires Python 3.6+

- flask_appbuilder/api/__init__.py
I was hitting a hard to interpret stack trace error message when I
added a method to `ModelRestApi`. (I went from using `ModelRestApi` to
using `BaseSupersetModelRestApi`).
This simple fix should prevent that.
Stack trace:
```
File "/Users/maximebeauchemin/code/superset/superset/app.py", line 183, in init_views
appbuilder.add_api(DatabaseRestApi)
File "/Users/maximebeauchemin/code/superset/env/lib/python3.6/site-packages/flask_appbuilder/base.py", line 532, in add_api
return self.add_view_no_menu(baseview)
File "/Users/maximebeauchemin/code/superset/env/lib/python3.6/site-packages/flask_appbuilder/base.py", line 509, in add_view_no_menu
baseview = self._check_and_init(baseview)
File "/Users/maximebeauchemin/code/superset/env/lib/python3.6/site-packages/flask_appbuilder/base.py", line 354, …
```
> fix: using default method name when unspecified in method_permission_name dict

- flask_appbuilder/__init__.py
- flask_appbuilder/api/__init__.py
- flask_appbuilder/baseviews.py
- flask_appbuilder/filters.py
- flask_appbuilder/templates/appbuilder/general/lib.html
- flask_appbuilder/tests/test_api.py
Exclude route methods on MVC and `include_route_methods` on API that will work like a white list
Default MVC endpoints method names are:
- api
- api_read
- api_get
- api_create
- api_update
- api_delete
- api_column_add
- api_column_edit
- api_readvalues
- list
- show
- add
- edit
- delete
- download
- action
- action_post
> [mvc] [api] New, exclude route methods

- examples/crud_rest_api/app/api.py
- flask_appbuilder/api/__init__.py
Makes it possible to override OpenAPI specs for methods that are usually defined on the method's doc itself
This override will make a dict update with the spec defined on the doc itself, for example:
``` python
class ContactModelApi(ModelRestApi):
resource_name = "contact"
datamodel = SQLAInterface(Contact)
allow_browser_login = True
openapi_spec_methods = {
"get_list": {
"get": {
"description": "Get all contacts, filter and pagination",
}
}
}
```
Will use the automatic `get_list` spec and adds a custom description for the method
> [api] new, override merge openapi docs specs

- flask_appbuilder/api/__init__.py
Simple fix for CRUD REST API get_list openapi spec, missing count attr
> [api] Fix, missing count fields on crud get list openapi spec

- setup.py
Closes #1265
The changelog for Flask-Babel 1.0.0 is:
> # Changelog
> 
> ## v1.0.0 - 06/02/2020
> 
> Starting with version 1, flask-babel has changed to
> [Semantic Versioning][semver].
> 
> ### Changed
> 
> - pytz is an explicit dependency. (#14)
> - pytz.gae, used for Google App Engine, is no longer necessary and has been
>   removed. (#153)
> - Fixed a deprecated werkzeug import (#158).
> - Fix issues switching locales in threaded contexts (#125).
> Fix, Update version of Flask-Babel to support Werkzeug 1.0

- flask_appbuilder/filemanager.py
Set the executable bit so processes can read the directory.
Only make the directory writeable by its owner.
> [filemanager] Fix, use a sane mode for directories

- CHANGELOG.rst
- flask_appbuilder/__init__.py
New 2.2.4
Improvements and Bug fixes on 2.2.4
- Fix, [docs] read the docs requirements (#1288)
- New, [mvc] [security] toggle pvm, perm and vm mvc views config options (#1259)
- Fix, [docs] Update actions.rst (#1277)
- Fix, [docs] changelog formatting (#1286)
- Fix, [mvc] Use os.path.join for downloads (#1281)
- Fix, [filemanager] Fix, use a sane mode for directories (#1282)
- Fix, [docs] add missing import (#1278)
- Fix, [mvc] Use formatters_columns with show_fieldsets (#1280)
> Bump FAB to 2.2.4

- setup.py
This makes it easier to combine FAB with other packages that want newer marshmallow versions. 
Fixes #1133
Replaces #1134 which was closed.
> Fix, Soften marshmallow version restriction

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release 2.3.0
Improvements and Bug fixes on 2.3.0
- New, [i18n] Add korean language (#1297)
- New, [api] support one to many relations (#1307)
- Fix, [mvc] reverts select2 to version 3.5.2 (#1308)
- Fix, [mvc] Upgrade to Jquery 3 and select2 4
- Fix, [api] List filters validation schema (#1303)
- Fix, [api] Soften marshmallow version restriction (#1295)
- Fix, [mvc] GET delete and action endpoints (#1294)
- Fix, [style] impose black code style (#1292)
> Release 2.3.0

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Improvements and Bug fixes on 2.3.1
[dependencies] Fix, marshmallow 3 breaks compat (#1333)
> Bump to 2.3.1

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release 2.3.4
Improvements and Bug fixes on 2.3.4
- Fix, [api] SQL selects and many to many joins (#1361)
- Fix, [frontend] Revert "Bump jQuery to 3.5 (#1351)" (#1363)
> Bump to 2.3.4

- flask_appbuilder/security/sqla/models.py
While working with apache-airflow when we enable rbac, all the tables related to flask-ui are added into the metadata. On that note, system tries to insert the rows in ab_view_menu table with respect to all the available DAGs. The length of the dag_id is 250 chars but in ab_view_menu the aligned column's (name) length is 100 chars and in turn value is truncated. Thereafter, it throws the Integrity Error when tries to insert the same value of name because of the truncation. And finally database goes down.
So, to improve this, we need to keep in sync with the ab_view_menu table. For that, I need to change the size of the column from 100 to 250.
https://github.com/dpgaspar/Flask-AppBuilder/issues/1367
> Fix, name column resizing in ab_view_menu table #1367

- flask_appbuilder/templates/appbuilder/general/lib.html
It seems to me like proper bootstrap panels should have a header and a body.
> fix: add a panel body to panel_begin/panel_end macros

- setup.py
#1334 started using this class, but didn't update the requirements in setup.py, so it would fail in an existing environment
> SQLAlchemyAutoSchema needs marshmallow-sqlalchemy>=0.22.0

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_api.py
This fix introduces inner queries so that many to many relations are not truncated, so now the limit and offset is applied on the inner query allowing for a result to have more rows then the limit caused by a many to many or many to one relation.
> Fix, load options and limits for many to many truncating results

- docs/config.rst
- examples/oauth/config.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/tests/_test_oauth_registration_role.py
- requirements-dev.txt
- requirements.txt
- setup.py
This PR brings dynamic user role on registration based on OAuth userinfo.
The current approach sets static `AUTH_USER_REGISTRATION_ROLE` for all users if self-registration is enabled. In our case, with OAuth authentication on GSuite domain (with FAB being auth engine for Airflow), we'd like to set team members as Admins and every other employee as read-only user ("Viewer"). 
This PR implements method that is used in Grafana ([docs](https://grafana.com/docs/grafana/latest/auth/generic-oauth/#jmespath-examples)), it uses [JMESPath](https://jmespath.org/) to resolve the role from userinfo retrieved from OAuth. It's quite flexible, as some OAuth providers return only username (like Google does), but others, like Okta, can return groups, so they can be utilized by the dynamic expression.
If …
> New, Dynamic user registration role

- flask_appbuilder/api/__init__.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/menu.py
- flask_appbuilder/security/api.py
Improve the builtin OpenAPI spec by adding descriptions and examples
@villebro
> New, add API descriptions and examples to OpenAPI spec

- flask_appbuilder/templates/appbuilder/general/lib.html
Fixed action disabling.
When using action with `confirmation=None`, a confirmation dialog still popups, with `None` message.
This is because the `None` Python value is translated in a `None` Javascript string, which is different from a `null` value and then `!!confirmation` is always `true`.
The fix checks for a `None` string value and convert it to a `false` Javascript value.
> Fix, action confirmation disabling

- docs/security.rst
- examples/oauth/app/security.py
- examples/oauth/app/views.py
- examples/oauth/config.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/security/views.py
As documented in https://github.com/dpgaspar/Flask-AppBuilder/issues/748, flask-oauthlib has been deprecated in favour of authlib.  In this issue, authlib being licensed under AGPL was a blocker, but Authlib is now licensed under BSD.
This patch updates code, docs and example code to use authlib instead of flask-oauthlib.
I've tested login against all the supported OAuth  providers except LinkedIn, for which I don't have the necessary credentials.
> fix: replace deprecated flask-oauthlib with authlib

- docs/rest_api.rst
- flask_appbuilder/api/manager.py
- flask_appbuilder/menu.py
- flask_appbuilder/security/api.py
Minor breaking changes here:
- to access Swagger UI you now go to http://localhost/swagger/v1 instead of http://localhost/swaggerview/v1
OpenApi tag name changes, minor cosmetic
> fix, change openapi tags and swagger access URL (breaking)

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release 3.0.0
Change log:
- Fix, swagger test (#1423)
- Fix, change openapi tags and swagger access URL (breaking) (#1422)
- Fix: replace deprecated flask-oauthlib with authlib (#1411)
- Refactor: interface query on m-m joins and select specific columns (#1398)
- Fix, docs on has_view_access (#1419)
- New, Examples/react api (#1071)
- Fix, action confirmation disabling (#1408)
- New, add API descriptions and examples to OpenAPI spec (#1396)
- New, Dynamic user registration role (#1410)
- Fix, typos and improved bit of the German translation (#1406)
- New, Added Dutch language to docs (#1393)
- New, Added Dutch translation (#1387)
- Fix, load options and limits for many to many truncating results (#1389)
- Fix, SQLAlchemyAutoSchema needs marshmallow-sqlalchemy>=0.22.0 (#1392)
- New, [api] …
> release: 3.0.0

- .github/PULL_REQUEST_TEMPLATE.md
- .github/prlint.json
- CONTRIBUTING.rst
- docker-compose.yml
- requirements-dev.txt
- requirements-extra.txt
- tox.ini
Help contributions by adding a docker-compose file and show how to setup a dev env and running tests
> docs: improve, help contributions

- flask_appbuilder/security/sqla/manager.py
@dpgaspar I'm not sure if this is merely a red herring (tracking down the root cause of a non-thread safe operation can be challenging) but per https://github.com/apache/incubator-superset/pull/10427 we were seeing issues with PyMySQL producing errors of the form,
```
pymysql.err.InternalError: Packet sequence number wrong - got 4 expected 1
```
which seems to indicate that there is some non-thread-safe activity. The code where the error was being thrown was the `count_users` method. Per the documentation there's no indication that the [`select_from`](https://docs.sqlalchemy.org/en/13/orm/query.html#sqlalchemy.orm.query.Query.select_from) method is not thread-safe but when I applied the proposed change it seemed to remedy the problem.
cc: @etr2460
> fix: Update SQLAlchemy query for count_users

- flask_appbuilder/babel/views.py
Fixes: https://github.com/dpgaspar/Flask-AppBuilder/issues/1459
Previously, FAB did not check if a locale is supported before attempting to load it. Now the check is performed and a 404 is given if the locale is not supported.
> fix: check if locale exists before loading it

- flask_appbuilder/api/convert.py
Now that FAB supports marshmallow>=3, there is no need for the `strict` option.
> refactor: remove unnecessary strict option from schemas

- docs/security.rst
- flask_appbuilder/security/manager.py
After successful authentication against the OpenShift built-in
OAuth provider, retrive the username.
Example OAuth Provider configuration, assuming that the Flask
application is running in the container on OpenShift:
```
OAUTH_PROVIDERS = [
{
"name": "openshift",
"icon": "fa-circle-o",
"token_key": "access_token",
"remote_app": {
"client_id": "system:serviceaccount:mynamespace:mysa",
"client_secret": "<mysa serviceaccount token here>",
"api_base_url": "https://openshift.default.svc.cluster.local:443",
"client_kwargs": {"scope": "user:info"},
"redirect_uri": "https://myapp-mynamespace.apps.<cluster_domain>",
"access_token_url": "https://oauth-openshift.apps.<cluster_domain>/oauth/token",
"authorize_url": "https://oauth-openshift.apps.<cluster_domain>/oauth/authorize", …
```
> [Feat] Support for OpenShift OAuth

- flask_appbuilder/static/appbuilder/js/ab.js
Select2 readonly extra class was no longer working after select2 version bump
> fix(js): select2 readonly not working

- flask_appbuilder/models/sqla/interface.py
When using models with multiple M-O to the same table and M-M references also, results from the later M-O get "overlapped" by the first reference. This PR aliases all relations and improves eager loading, improving performance also.
> fix(api): inner joins eager loading

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_mvc.py
The refactor in #1398 changes the `get()` function, and mistakenly
always applied the PK filter, even in the case of composite keys.
(The else block of `if self.is_pk_composite` applied it again, so it was
actually applying the same filter twice, which didn't break anything,
but was not needed)
I had a bit of trouble running the tests locally, but by ignoring some bits that weren't working for me I was able to validate that the block I added behaves as expected.
Discovered in Airflow, https://github.com/apache/airflow/issues/11513
The stack trace we got was:
```
File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
response = self.full_dispatch_request()
File "/home/airflow/.local/lib/python3.6/site-packages/flask/app.py", line 1952, in …
```
> Fix "actions" on ModelViews with composite primary keys

- examples/quickhowto2/app/static/angularAssets/abBtnDelete.html
- examples/react-rest-api/app/static/src/components/CRUDButtons.js
- flask_appbuilder/templates/appbuilder/general/lib.html
This is subjective, but I don't believe the "eraser" icon used for destructive actions does the best job at clearly communicating its purpose, especially when the icon is used alone without associated text (until you hover to see tooltip). To be honest, I wasn't actually sure what the icon was a picture of until I saw the markup. This update simply swaps all instances out for the "trash" icon from the same Feather Icons library.
| Before | After |
|---|---|
| ![image](https://user-images.githubusercontent.com/3267/97007271-2981d780-150f-11eb-902c-36fe25f229a1.png) | ![image](https://user-images.githubusercontent.com/3267/97007233-1bcc5200-150f-11eb-9b33-86c11eb0b2b9.png) |
> style: Use a clearer visual representation for "delete" actions

- flask_appbuilder/templates/appbuilder/general/lib.html
Small UX improvement. Moves the caret next to "Search" within the clickable target so the accordion toggles when it is clicked as well.
| Before | After |
|---|---|
| ![Screen Recording 2020-10-22 at 05 13 25 PM](https://user-images.githubusercontent.com/3267/96930712-24c71000-148a-11eb-9204-db8c58b35f64.gif)  | ![Screen Recording 2020-10-22 at 05 12 47 PM](https://user-images.githubusercontent.com/3267/96930718-27296a00-148a-11eb-89b6-82bd368068b0.gif)  |
> Fix: Improve UX by moving drop-down caret within clickable target

- examples/quickhowto2/app/static/angularAssets/abModelSearch.html
- examples/quickhowto2/app/templates/list_angulajs.html
- flask_appbuilder/static/appbuilder/css/ab.css
- flask_appbuilder/templates/appbuilder/general/widgets/search.html
Redo of #1491
This time leaving the `filter` class in place that is utilized by scripting, but still removing the undesired styling associated with it.
Adhering to [Bootstrap's Dropdown guidelines](https://getbootstrap.com/docs/3.3/components/#dropdowns), the anchors within dropdown elements should not have any styled CSS classes on them. This PR removes the `btn` classe added in FAB as they were yielding undesirable side effects (see [Airflow patch fix](https://github.com/apache/airflow/pull/11752)).
The `.btn.filter` styling that I removed in this PR appears to have been added by #493, but was likely only needed to begin with because of the presence of the `btn` class (which center aligned the text). 
| Before | After |
|---|---|
| <img width="272" alt="Image 2020-10-22 at 4 31 32 PM" …
> fix: remove unnecessary CSS class/styling from dropdowns

- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_mvc.py
fix MVC order by related fields (use aliased join)
> fix: MVC order by related column use alias

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release 3.1.1
```
Improvements and Bug fixes on 3.1.1
fix: MVC order by related column use alias (#1504) [Daniel Vaz Gaspar]
fix: remove unnecessary CSS class/styling from dropdowns (#1503) [Ryan Hamilton]
deps: constraint pre 1 packages following semver (#1502) [Daniel Vaz Gaspar]
fix: MVC order by on relation (#1500) [Daniel Vaz Gaspar]
docs: add github actions badge (#1501) [Daniel Vaz Gaspar]
fix: remove unnecessary classes from dropdowns (#1491) [Ryan Hamilton]
ci: migrate from travis to github actions (#1497) [Daniel Vaz Gaspar]
fix: lint (#1498) [Daniel Vaz Gaspar]
fix: Improve UX by moving drop-down caret within clickable target (#1492) [Ryan Hamilton]
style: use a clearer visual representation for "delete" actions (#1495) [Ryan Hamilton]
fix: …
```
> release: 3.1.1

- .github/workflows/ci.yml
Fix github actions: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> fix: github actions

- flask_appbuilder/security/views.py
- setup.py
```
ERROR:flask_appbuilder.security.views:Error on OAuth authorize: 'str' object has no attribute 'decode'
```
Fixes #1511
> fix: oauth #1511

- examples/base_api/README.rst
- examples/crud_rest_api/README.rst
- examples/react-rest-api/README.rst
The specified swagger path in the readme (http://localhost:5000/swaggerview/v1) does not work. Instead http://localhost:5000/swagger/v1 works.
> docs: fix, swagger path in readme

- flask_appbuilder/templates/appbuilder/general/lib.html
Fixes: #1529 
Action confirmation set to None is not respected when using single on a show view
> fix(mvc): action confirmation on single show view

- flask_appbuilder/api/__init__.py
- flask_appbuilder/api/convert.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/tests/config_api.py
Fixes the name collision on OpenAPI spec for auto generated nested schemas. Previously schema names were getting named "Meta1", "Meta2" etc.. this PR prefixes the schema name with the schema parent name and sufixes with the model name.
> fix(api): OpenAPI spec of nested components without auto generated names

- setup.py
Latest SQLAlchemy 1.4.0 break compatibility with sqlalchemy-utils and flask-sqlalchemy
Issues:
https://github.com/pallets/flask-sqlalchemy/issues/910
https://github.com/apache/superset/issues/13631
> fix: sqlalchemy 1.4.0 breaking changes

- flask_appbuilder/security/manager.py
> fix: load user info for okta

- flask_appbuilder/baseviews.py
Purely docstring changes. No touch on actual code.
These two docstring errors are affecting:
- https://flask-appbuilder.readthedocs.io/en/latest/api.html#flask_appbuilder.baseviews.BaseModelView.search_form_extra_fields
and
- https://flask-appbuilder.readthedocs.io/en/latest/api.html?highlight=base_filters#flask_appbuilder.baseviews.BaseModelView.search_form_query_rel_fields
> docs: Fix errors in BaseModelView docstring

- flask_appbuilder/security/manager.py
When `given_name` field does not exist in AzureAD, users can't login.
I explicitly claimed `given_name` field in AzureAD, however, `given_name` field does not exist because it is empty.
Therefore, the changes are to relax mandatory fields in AzureAD.
Fix the issue: #1612
> 2021-04-13 04:53:27,972:ERROR:flask_appbuilder.security.views:Error returning OAuth user info: 'given_name'
> fix: relax AzureAD mandatory fields

- flask_appbuilder/security/manager.py
- flask_appbuilder/tests/_test_auth_ldap.py
LDAP referrals are completely broken anyway, and we've already set
`ldap.OPT_REFERRALS` to 0, so there is no reason to care about these.
Thus the presence of referrals alone should not cause authentication of
a user to fail due to multiple results being returned.
Fixes issue #1581.
If this change is not desired, and rather a documentation update to
indicate that setting up LDAP against Microsoft AD requires a
organizational unit to be specified in the LDAP search base, and I
happy to make that update.  I can add the necessary tests once I get
feedback if we want to move forward with this.
> fix: Ignore LDAP search referrals

- flask_appbuilder/security/manager.py
- flask_appbuilder/security/sqla/manager.py
- flask_appbuilder/tests/base.py
- flask_appbuilder/tests/config_security.py
- flask_appbuilder/tests/test_security_permissions.py
Add a new security manager API method to fetch a user permissions, these permissions can be a mix between builtin roles and DB roles. The actual permission fetching from the DB is efficient (single query), avoids the N+1 issue.
`get_user_permissions`
> feat(security): get user permissions API

- flask_appbuilder/security/sqla/manager.py
Uses eager loading for fetching role permissions. Improved performance. Previously when accessing `view_menu.name` would result on executing a new query (lazy loading)
> fix: improve performance for get role permissions

- docs/api.rst
- flask_appbuilder/api/__init__.py
- flask_appbuilder/baseviews.py
- flask_appbuilder/hooks.py
- flask_appbuilder/tests/test_api.py
- flask_appbuilder/tests/test_mvc.py
This PR adds support for a `before_request` hook that can be used in FAB's view and API classes to execute some code just before the route handler is invoked. It has the same semantics as Flask's `before_request`, but it is scoped only to the routes within a given FAB class and can be scoped even further to a subset of handlers within the class.
```python
@before_request
def ensure_feature_is_enabled(self):
if self.feature_is_disabled:
return self.response_404()
return None
```
```python
@before_request(only=["create", "update", "delete"])
def ensure_write_mode_enabled(self):
if self.read_only:
return self.response_400()
return None
```
_It seems like we could implement the conditional logic directly in route handlers. Why do we need a new pattern?_
In many cases, implementing the …
> feat: Add support for before_request hooks

- flask_appbuilder/base.py
- flask_appbuilder/menu.py
- flask_appbuilder/tests/test_menu.py
This is "part 2" of https://github.com/dpgaspar/Flask-AppBuilder/pull/1629. It adds support for conditionally rendering menu items at request time.
@dpgaspar the tests for the menu piece specifically are not very comprehensive but I think we should get more confidence around this code. Do you have a preference for how you'd like to expand upon these tests? The menu code is almost entirely self-contained, so IMO we should pass the one non-self-contained piece (`current_app`) which let's us easily stub that value and unit test the code. That should give us all we need, since this is already tested from API PoV. Thoughts?
Also, let me know what other (if any) docs you think should be added here.
> feat: Support for conditional menu item rendering

- docs/advanced.rst
- flask_appbuilder/models/decorators.py
* The code that describes the usage of the `@renders` decorator does not
refer to `self` despite using a class variable. This commit fixes the
problem.
Signed-off-by: mr.Shu <mr@shu.io>
> fix: Missing `self` reference for my_custom

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Patch release: 3.3.1
- fix: Handle integrity fails if groups map to same roles (#1605) [Fred Thomsen]
- refactor: OAuth - redirect direct to provider if just one provider exists (#1618) [hyunjong.lee]
- feat: Allow using custom Swagger template for SwaggerView. (#1639) [Cristòfol Torrens]
- chore: Remove polyfill shims for browsers no longer supported (#1606) [Ryan Hamilton]
- docs: Missing `self` reference for my_custom (#1651) [Marek Šuppa]
- fix: add warning text to roles when AUTH_ROLES_SYNC_AT_LOGIN (#1642) [Daniel Vaz Gaspar]
> release: 3.3.1

- requirements.txt
- setup.py
Fixes https://github.com/dpgaspar/Flask-AppBuilder/pull/1685
> chore: bump prison version

- requirements.txt
Bump Flask-OpenID on the requirements, more details on the issue bellow
> chore: Bump flask-openid to 1.3.0

- docs/rest_api.rst
* Wrong property name. It was `base_route` but should have been `route_base`
> docs: fix issue 1700

- flask_appbuilder/fields.py
Stop using python2 compatible types.
> fix: ModuleNotFoundError from wtforms 3.0.0

- requirements.txt
- setup.py
Pin down WTForms, fixes: https://github.com/dpgaspar/Flask-AppBuilder/issues/1732
> chore: pin down WTForms

- flask_appbuilder/fieldwidgets.py
- flask_appbuilder/upload.py
- requirements-extra.txt
Bump up `requests` to 2.26.0
Move from HTMLString to Markup due deprecation warnings
> - https://github.com/dpgaspar/Flask-AppBuilder/issues/1721
> - https://github.com/dpgaspar/Flask-AppBuilder/issues/1692
> chore: [Deprecation] Use Markup instead of HTMLString

- flask_appbuilder/security/views.py
Adds the ability to redirect to a URL as defined in the query params `next_url` after login.
> chore: Redirect to prev url on login

- docs/config.rst
- flask_appbuilder/security/decorators.py
- flask_appbuilder/tests/config_api.py
- flask_appbuilder/tests/test_api.py
Adds a temporary flag named `AUTH_STRICT_RESPONSE_CODES` that enables strict (correct) authorization HTTP responses, instead of 401 sends 403 when a user is not authorized to make a request to an endpoint.
> fix: optionally return HTTP 403 instead of 401 when unauthorized

- docs/security.rst
Fixed indentation of password validation function example
> docs: Fix indentation of function content

- flask_appbuilder/security/decorators.py
- flask_appbuilder/tests/base.py
- flask_appbuilder/tests/test_mvc.py
> fix: optional unauthorized status codes

- docs/security.rst
- flask_appbuilder/security/manager.py
AUTH_ROLES_MAPPING is not currently not support using the Azure provider.
This branch will mimicking what has been done for Okta and add the single line of code: "role_keys": data.get("groups", []) in the return dictionary for the provider Azure
> feat: Adding role_keys into Azure OAuth

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release 3.4.1:
```
- feat: Adding role_keys into Azure OAuth (#1744) [Michael Yee]
- docs: Fix small documentation issues (#1755) [Dosenpfand]
- fix: 1154 Add LOGOUT_REDIRECT_URL setting (#1749) [blag]
- fix: optional unauthorized status codes (#1753) [Daniel Vaz Gaspar]
- docs: Fix indentation of function content (#1752) [akettmann-e24]
- fix: optionally return HTTP 403 instead of 401 when unauthorized (#1748) [Daniel Vaz Gaspar]
- chore: Redirect to prev url on login (#1747) [Geido]
- docs: add aws cognito setup code examples (#1746) [Pin Jin]
- fix: Added sr-only class to icon only links (#1727) [Thomas Stivers]
- chore: [Deprecation] Use Markup instead of HTMLString (#1729) [Andrey Polegoshko]
```
> release: 3.4.1

- flask_appbuilder/tests/security/test_auth_ldap.py
- flask_appbuilder/tests/security/test_auth_oauth.py
- flask_appbuilder/tests/test_api.py
The deprecated unittest aliases were removed in python/cpython#28268
> chore: Use assertEqual instead of assertEquals for Python 3.11 compatibility

- examples/crud_rest_api/app/api.py
- flask_appbuilder/api/__init__.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/tests/test_api.py
The `FAB_ADD_OPENAPI_VIEWS` was not being evaluated anywhere on the code. The reference was to `FAB_ADD_SECURITY_VIEWS`
> fix: openapi on and off config flag

- flask_appbuilder/security/views.py
Currently the call to `authorize_access_token` in `oauth_authorized` is not wrapped in exception handling. As a result when an error occurs in the OAuth flow, a 500 response is generated and the user sees an error page. This may lead to a bad user experience, because the user is not able to fix the problem in any way on their own.
This PR adds an error handling, so that any error will be caught and the user is redirected to the login page with the appropriate flash error message.
> fix: Handle authorize_access_token exception

- flask_appbuilder/security/views.py
- flask_appbuilder/tests/security/test_mvc_security.py
Role and Confirm password field in user db model view were not marked as required field, so added those validators.
> fix: Set role and confirm password while adding user mandatory

- flask_appbuilder/fieldwidgets.py
- flask_appbuilder/security/forms.py
- flask_appbuilder/security/views.py
Small fix for https://github.com/dpgaspar/Flask-AppBuilder/pull/1758, where the error message (shown by the browser) is not show to the user, not adding a new user without any information.
The console log shows: 
```
An invalid form control with name='roles' is not focusable.
```
> fix: required roles on user form not showing error msg

- flask_appbuilder/api/__init__.py
- flask_appbuilder/api/manager.py
- flask_appbuilder/templates/appbuilder/swagger/swagger.html
Fix swagger servers to be actual servers that can be overridden by setting `FAB_OPENAPI_SERVERS`.
This change will make all endpoints on swagger be declared by their full relative path instead of just using `resource_name`.
Before:
After:
REST API that use `route_base` will now work!
> fix: make servers be actual servers on swagger, full endpoint paths

- docs/config.rst
Adds a missing doc key `FAB_OPENAPI_SERVERS`
> docs: adds missing config key FAB_OPENAPI_SERVERS

- flask_appbuilder/security/manager.py
- flask_appbuilder/tests/security/test_base_security_manager.py
This PR moves one line around so the `user.last_login` field is only updated when the user has successfully authenticated.
Without this PR the `user.last_login` field is not very useful, as an attacker trying to brute force a login would continuously update the `last_login` field to the datetime of the latest _unsuccessful_ authentication attempt, instead of the datetime of the last successful authentication attempt. I believe that "login" usually refers to a successful authentication attempt, so this keeps the behavior of the code consistent with the semantics of the field name.
I don't have a thorough understanding of what all `user.last_login` could be/is used for, but I can imagine that, when it records the last datetime of successful authentication attempt, it can be combined with …
> fix: Only update user.last_login on successful authentication

- flask_appbuilder/cli.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/security/mongoengine/manager.py
- flask_appbuilder/security/sqla/manager.py
- flask_appbuilder/tests/test_fab_cli.py
Expose `json.dump(indent=*)` to the `fab export-roles --indent=*` CLI command.
> feat(cli): allow `export-roles` to be beautified

- docs/i18n.rst
- docs/versionmigration.rst
The doc in master regarding i18 still reference the not used anymore by `flask_appbuilder` fork `flask_babelpkg` for multiple translations.
This PR fixes that by:
- Updating the i18 doc from references to flask_bablepkg fork as is not used anymore as stated in the version migration
- minor typos encountered along the way of updating i18 doc from `flask_bablepkg` to `flask_babel`
> docs: Update doc i18 to flask_babel

- flask_appbuilder/security/views.py
- flask_appbuilder/tests/base.py
- flask_appbuilder/tests/security/test_mvc_security.py
- flask_appbuilder/utils/base.py
Fixes next URL logic for OAuth, OID and DB
> fix: next url on login (OAuth, OID, DB)

- rtd_requirements.txt
> fix: doc requirements

- flask_appbuilder/security/sqla/manager.py
Noop on auth db fake update user is explicitly using the `User` model instead of `self.user_model` this causes issues with custom User models
> fix: noop user update on Auth db, use set user model

- docs/config.rst
Add `FAB_ADD_SECURITY_API` config option to the docs, for the new CRUD REST API for the security models, still on Beta phase.
> docs: add FAB_ADD_SECURITY_API config option

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Patch release 4.1.1
```
- fix: custom security class import, bad cast (#1851) [Daniel Vaz Gaspar]
- fix: Set certificates before reconnecting to LDAP (#1846) [Sebastian Bernauer]
```
> release: 4.1.1

- flask_appbuilder/tests/test_urltools.py
- flask_appbuilder/urltools.py
Fixes a bug when a `ModelView` has declared `search_columns` and `search_exclude_columns` was still possible to filter by these fields when calling explicitly the URL with the filter format on the query parameters.
cc: @thesuperzapper @z-arosio
> fix(MVC): discard excluded filters from query

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release: 4.1.2
- fix: remove sqlite dbs from examples (#1853) [Daniel Vaz Gaspar]
- fix(MVC): discard excluded filters from query (#1862) [Daniel Vaz Gaspar]
> release: 4.1.2

- flask_appbuilder/security/sqla/manager.py
1. We found that if setting up a sqla callback on PVM, the permission and vm fields are not set but only their IDs. It will cause extra lookup downstream for those fields. 
2. By pre-populating those fields, we both set their IDs and fields
> fix: populating permission and vm instead of just setting the id

- docs/security.rst
Adds a responsible disclosure text to docs and to github security policy
> docs: add responsible disclosure text to security

- flask_appbuilder/api/__init__.py
responses should be registered with apispec using components.response();
not by directly modifying the _reponses dict, which is internal to the
ApiSpec.Components class.
Also, handle duplicate response registrations gracefully.
> fix(api): register responses with apispec using components.response()

- flask_appbuilder/base.py
- flask_appbuilder/tests/templates/custom_index.html
- flask_appbuilder/tests/test_custom_indexview.py
Fixes custom menu, based on: https://github.com/dpgaspar/Flask-AppBuilder/pull/1875
> fix: custom menu option

- docs/security.rst
- examples/oauth/app/security.py
- examples/oauth/app/views.py
- examples/oauth/config.py
- setup.py
Allows `authlib` > 1 extra dependency. Related issues:
https://github.com/dpgaspar/Flask-AppBuilder/issues/1861
https://github.com/dpgaspar/Flask-AppBuilder/issues/1821
https://github.com/apache/superset/issues/13948
cc: @thesuperzapper @potiuk @shawnzhu
> chore: allow authlib > 1 updated docs

- flask_appbuilder/templates/appbuilder/general/security/login_oauth.html
Due to Jinja autoescaping, when we render the `next` url in html the `&` become escaped to `&amp;`
This result in a wrong URL parameters.
For example
`?next=https://www.abc.com?id=1&name=a` will be rendered as `?next=https://www.abc.com?id=1&amp;name=a` in HTML page.
The fix is to hint Jinja not to escape the URL and also encode the URL.
> fix: fix a wrong 'next' URL in javascript

- CHANGELOG.rst
- flask_appbuilder/__init__.py
Release: 4.1.4
Change log:
```
- chore: Redirect to prev url on login for AuthRemoteUserView (#1901) [Alexander Ryndin]
- chore: Bump upper bounds on wtforms and flask-wtf (#1904) [Tomáš Drtina]
- fix(mvc): related model view setting default related field value (#1898) [Daniel Vaz Gaspar]
- fix: DateTimePicker rendering in forms (#1698) [Federico Padua]
- test(fab_cli): tag tests that need internet so they can be skipped (#1880) [jnahmias]
- fix: fix a wrong 'next' URL in javascript (#1897) [Sansarun Sukawongviwat]
- chore: allow authlib > 1 updated docs (#1891) [Daniel Vaz Gaspar]
- docs: fix oauth example config (#1890) [Daniel Vaz Gaspar]
- docs: fix oauth example config (#1889) [Daniel Vaz Gaspar]
```
> release: 4.1.4

- flask_appbuilder/security/manager.py
- flask_appbuilder/security/sqla/manager.py
- flask_appbuilder/tests/test_security_permissions.py
Adds an efficient utility method for fetching all roles and perms for a user, just implemented for SQLAlchemy.
> feat: add utility method on SM for fetching all roles and perms for a user

- flask_appbuilder/views.py
Replace attachment_filename with download_name, as it has been removed from flask. Fixes #1947
> fix: Replace deprecated attachment_filename

- flask_appbuilder/models/sqla/interface.py
A rehash of https://github.com/dpgaspar/Flask-AppBuilder/pull/1959 but, per https://github.com/dpgaspar/Flask-AppBuilder/pull/1959#issuecomment-1347645811, rather than explicitly defining the form of the relationship loading rely instead on the implicit definition of the specific model relationships (which defaults to lazy per [here](https://docs.sqlalchemy.org/en/14/orm/relationship_api.html#sqlalchemy.orm.relationship.params.lazy)). This helps to ensure that the optimal loading technic is used for each specific implementation/use case.
See [Relationship Loading Techniques](https://docs.sqlalchemy.org/en/14/orm/loading_relationships.html#relationship-loading-techniques) for the various relationship loading techniques which are supported by SQLAlchemy which fall into one of three …
> chore: Use implicit default loading rather than explicit joined eager loading

- flask_appbuilder/api/__init__.py
- flask_appbuilder/tests/test_api.py
When a developer defines an invalid search filter on `ModelRestApi` a warning is issued at bootstrap but `_info` metadata endpoint crashes with HTTP 500
> fix(api): _info HTTP 500 when exists a defined invalid search field

- examples/crud_rest_api/testdata.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/sqla/models.py
- flask_appbuilder/tests/test_api.py
Fixes `ModelRestApi` one to one relation when it's defined like:
```python
class Child(Model):
id = Column(Integer, primary_key=True)
name = Column(String(50), unique=True, nullable=False)
parent_id = Column(Integer, ForeignKey("contact.id"))
parent = relationship("Parent", back_populates="child")
class Parent(Model):
id = Column(Integer, primary_key=True)
name = Column(String(150), unique=True, nullable=False)
child = relationship("Child", back_populates="parent", uselist=False)
```
@hughhhh
> fix: REST API one-to-one relationship

- flask_appbuilder/api/__init__.py
When the exception is logged it might cause another exception:
```
2023-01-31 11:09:00,239:ERROR:superset.views.base:_log() got an unexpected keyword argument 'exc_info'
Traceback (most recent call last):
File "/opt/superset/lib/python3.9/site-packages/flask_appbuilder/api/__init__.py", line 109, in wraps
return f(self, *args, **kwargs)
File "/opt/superset/lib/python3.9/site-packages/superset/views/base_api.py", line 113, in wraps
raise ex
File "/opt/superset/lib/python3.9/site-packages/superset/views/base_api.py", line 110, in wraps
duration, response = time_function(f, self, *args, **kwargs)
File "/opt/superset/lib/python3.9/site-packages/superset/utils/core.py", line 1524, in time_function
response = func(*args, **kwargs)
File …
```
> fix: don't use root logger

- flask_appbuilder/forms.py
Remove the unused parameter `allow_blank` from the instantiation of the `QuerySelectMultipleField` object to avoid throwing the warning:
```
fields.py:179: UserWarning: allow_blank=True does not do anything for QuerySelectMultipleField.
```
> fix: Remove unused parameter from QuerySelectMultipleField instantiation

- .github/workflows/ci.yml
- requirements-extra.txt
Hopefully permanently fixes CI error:
```
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DPYODBC_VERSION=4.0.30 -I/opt/hostedtoolcache/Python/3.8.16/x64/include/python3.8 -c src/buffer.cpp -o build/temp.linux-x86_64-3.8/src/buffer.o -Wno-write-strings
In file included from /usr/include/sql.h:19:0,
from src/pyodbc.h:56,
from src/buffer.cpp:12:
/usr/include/sqltypes.h:56:10: fatal error: unixodbc.h: No such file or directory
#include "unixodbc.h"
^~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
[end of output]
```
related with: https://github.com/dpgaspar/Flask-AppBuilder/pull/1992
and: https://github.com/microsoft/linux-package-repositories/issues/36
> fix: CI broken by pyodbc vs unixodbc

- docs/security.rst
- flask_appbuilder/base.py
- flask_appbuilder/security/manager.py
- flask_appbuilder/tests/config_api.py
- flask_appbuilder/tests/config_oauth.py
- flask_appbuilder/tests/config_security.py
- flask_appbuilder/tests/config_security_api.py
- flask_appbuilder/tests/security/test_rate_limiter.py
Disable auth rate limiting by default, will break dependencies unit tests and integration tests
> fix: disable rate limit by default

- examples/extendsecurity/testdata.py
- flask_appbuilder/models/sqla/interface.py
- flask_appbuilder/tests/test_mvc.py
Description:
ADDITIONAL INFORMATION
Has associated issue:
> fix: using base_filters with FilterEqualFunction not working for relation fields

- docs/config.rst
- flask_appbuilder/cli.py
- flask_appbuilder/tests/test_fab_cli.py
Change `flask fab create-app` so that it initially asks for a `SECRET_KEY` help developers to bootstrap a secure app.
New behaviour:
``` bash
$ flask fab create-app
Your new app name: test1
Your engine type, SQLAlchemy or MongoEngine (SQLAlchemy, MongoEngine) [SQLAlchemy]:
Your app SECRET_KEY. It should be a long random string. Minimal size is 20: short_secret
Error: SECRET_KEY size is less then 20
Your app SECRET_KEY. It should be a long random string. Minimal size is 20: 5aNxw0NtC6QdloLtLAAUKE0Klu3TSTUAJp8OIdhqkpmFia/km2nizVfE
Downloaded the skeleton app, good coding!
```
> fix: cli create app ask for initial secret key

- .github/workflows/codeql-analysis.yml
- flask_appbuilder/security/api.py
First iteration on codeQL configuration was not correct, this one is heavily based on the default but should get things started
> ci: improve codeql configuration 

- flask_appbuilder/static/appbuilder/js/ab_filters.js
Update getting value of select2 according to their recomendation: https://github.com/select2/select2/blob/4de1d236e602149a5c78d35899b49b3989b94107/src/js/select2/core.js#L536
> fix: Update getting value usage.

- flask_appbuilder/security/manager.py
Small fix for an old copy pasta mistake
> fix: user registration menu name

- docs/config.rst
File config.py in Flask-AppBuilder-Skeleton has been renamed to [config.py.tpl](https://github.com/dpgaspar/Flask-AppBuilder-Skeleton/blob/master/config.py.tpl) and link to it in docs is broken now.
> fix: broken link to config.py template

- flask_appbuilder/templates/appbuilder/general/security/login_oauth.html
- flask_appbuilder/tests/test_mvc_oauth.py
Since next parameter shouldn't be used with `safe` Jinja filter (see https://github.com/dpgaspar/Flask-AppBuilder/pull/1978), to avoid double escaping we can use Jinja's `urlencode`. Also, it might be clearer to work with this parameter in the related libraries, no need to double unquote the url.
cc @gschuurman
> fix: Double escaping for next param in login with oauth

- docs/rest_api.rst
- examples/crud_rest_api/app/models.py
- flask_appbuilder/api/convert.py
- flask_appbuilder/tests/sqla/models.py
- flask_appbuilder/tests/test_api.py
- flask_appbuilder/tests/test_mvc.py
Using default marshmallow Enum by value option is a breaking change for FAB. This PR changes the Enum `by_value` default to True.
> fix: marshmallow enum by value keep compatibility

- setup.py
in commit 7f194cf, the tests package got moved from within the
'flask_appbuilder' namespace into the root namespace, but the package
was not explicitely excluded from the wheel in setuptools.
As a result, all the FAB tests would get installed into the 'tests'
package namespace during an installation of the FAB 4.3.4 wheel.
Furthermore, if other wheels would also ship modules inside the 'tests'
namespace, these modules would get overidden. Package managers like
`pip` probably wouldn't even notice.
But other package managers (e.g. `dpkg` or `rpm`) will detect such
conflicts and will complain about it loudly and refuse to install
packages with conflicting files.
> chore: dont add 'tests' package to wheel

- flask_appbuilder/templates/appbuilder/general/lib.html
Fix for reported issue: #2086
On user info view, reset my password action is incorrectly redirecting the user to user info view. Caused by https://github.com/dpgaspar/Flask-AppBuilder/pull/2075, both buttons have the same id so the click action get's triggered twice on this specific case reset my password executes twice so the last one will redirect to the second action user info view.
This PR makes the action button ids unique
> fix: MVC form action, broken reset my password

- examples/quicktemplates/app/templates/mybase.html
if those `include`s are not added, deletion of records is not working in this example
> fix: make deletion in quicktemplates example work again

- flask_appbuilder/templates/appbuilder/init.html
- flask_appbuilder/templates/appbuilder/swagger/swagger.html
> fix: swagger missing nonce

- docs/security.rst
- flask_appbuilder/security/manager.py
Should be "perform a search" not "preform"
> docs(typo): "preform" -> "perform" x4

- .readthedocs.yaml
Add readthedocs required config: https://blog.readthedocs.com/migrate-configuration-v2/
> docs: add RTD required config

- rtd_requirements.txt
> docs: fix RTD config requirements

- flask_appbuilder/fields.py
> fix: wtforms compat 3.1.0

- docs/security.rst
Help for: #1641
Improves LDAP auth docs
> docs: improve LDAP auth auth_roles_mapping

- flask_appbuilder/security/manager.py
- tests/security/test_auth_oauth.py
- tests/test_api.py
Keep backward compatibility with Azure, caused by this breaking change: #2121
although `id_token` does not include an `upn` field, it can optionally be included.
https://learn.microsoft.com/en-us/entra/identity-platform/id-token-claims-reference
On this change we use `upn` if it exists else use `email`
> fix: azure keep using upn if exists

- docs/security.rst
- flask_appbuilder/security/manager.py
- tests/security/test_auth_oauth.py
Supports Auth0 OAuth provider
Advised config:
``` python
OAUTH_PROVIDERS = [
{
"name": "auth0",
"icon": "fa-shield-halved",
"token_key": "access_token",
"remote_app": {
"client_id": os.environ.get("AUTH0_KEY"),
"client_secret": os.environ.get("AUTH0_SECRET"),
"api_base_url": f"https://{os.environ.get('AUTH0_DOMAIN')}/oauth2/v1/",
"client_kwargs": {"scope": "openid profile email groups"},
"access_token_url": f"https://{os.environ.get('AUTH0_DOMAIN')}/oauth/token",
"authorize_url": f"https://{os.environ.get('AUTH0_DOMAIN')}/authorize",
"server_metadata_url": f"https://{os.environ.get('AUTH0_DOMAIN')}/"
f".well-known/openid-configuration",
},
}
]
```
> feat: support Auth0 OAuth2

- flask_appbuilder/security/manager.py
- flask_appbuilder/security/views.py
- flask_appbuilder/templates/appbuilder/general/security/login_oid.html
- tests/config_oid.py
- tests/test_mvc_oauth.py
- tests/test_mvc_oid.py
- tests/test_security_api.py
On OpenID use the provider name instead of the URL, fetch the required URL from the app config
> fix: openID provider validation flow

- flask_appbuilder/security/manager.py
- tests/base.py
- tests/security/test_mvc_security.py
Make sure the when a user is made inactive any active sessions are not allowed to login
> fix: don't load inactive users with sessions

- docs/config.rst
- flask_appbuilder/security/manager.py
- flask_appbuilder/security/views.py
- tests/security/test_auth_oauth.py
- tests/security/test_auth_remote_user.py
A simple solution for: https://github.com/dpgaspar/Flask-AppBuilder/issues/2014
Add a new config key `AUTH_REMOTE_USER_ENV_VAR` to allow for users to set their own WSGI env var that holds the current username.
> feat: AUTH_REMOTE_USER_ENV_VAR config key for auth REMOTE_USER type

- docs/i18n.rst
Fixed broken link for Flask-Babel and typo.
> docs: updated Flask-Babel link and fix typo

- docs/security.rst
- flask_appbuilder/exceptions.py
- flask_appbuilder/security/manager.py
- tests/security/test_auth_oauth.py
Added [Authentik](https://goauthentik.io/) as new identity provider.
This PR includes:
- Authentik as new provider in the security manager.
- Role mapping from Authentik groups
- JWKS validation on Authentik tokens if provided in the config.py.
- New exception if token signature cannot be validated.
- Tests for the authentication for parsing the correct info, checking if the signature is valid and allowing unsigned tokens if specified in the config.
> feat: Added authentik as new identity provider

- flask_appbuilder/security/sqla/models.py
- flask_appbuilder/security/views.py
- tests/test_mvc.py
Fixes: #2073
adds lazy joined to permission view model (fixes N+1 issue) and removes `created_by` and `changed_by` from the user list search options so we don't load all users twice on page load.
> fix: performance issues on user and roles list

- docs/quickcharts.rst
docs:Update quickcharts.rst for typo gold to goal
docs:Update quickcharts.rst for typo gold to goal
> docs: Update quickcharts.rst to correct typo "gold" to "goal"

- flask_appbuilder/security/manager.py
We should check the errors for OKTA Oauth; if we do not check it, it will continue and will create a user with the default information that we create in the return clause.
Why does this happen?
Sometimes users are in more than 100 groups and Okta does not return all the groups and it return the following error message
```
User info from Okta: {'error': 'server_error', 'error_description': 'The groups claim matched too many groups and must be configured to match fewer groups.'}
```
It returns an error but, we do not check it and we let it to continue with the following return clause
```
return {
"username": "okta_",
"first_name": "",
"last_name": "",
"email": "",
"role_keys": [],
}
```
And with data with register a new user(s)  [here](https://github.com/dpgaspar/Flask-AppBuilder/blob/master …
> fix: Check if Oauth login with OKTA is correct

- flask_appbuilder/security/manager.py
Small change that makes integrating roles with Keycloak dramatically easier, i.e. stops requiring writing custom code.
(fix not feat because this should have been default and makes indirect usability of the library so much easier for users of Superset and the like)
Closes #1985
> fix: Keycloak OAuth2: get groups as role_keys per default

- CHANGELOG.rst
- flask_appbuilder/__init__.py
> release: 4.5.0

- flask_appbuilder/security/manager.py
flask-limiter will not obey to `RATELIMIT_KEY_FUNC`, this PR makes it possible to set this config
> fix: rate limiter key function

- requirements/extra.txt
chore: bump cryptography to 42.0.4
> chore: bump cryptography to 42.0.4

- docs/conf.py
This will replace the hardcoded year in the copyright part of docs with `datetime.now().year`
> fix: hardcoded year removed from copyright

- .github/workflows/ci.yml
- flask_appbuilder/security/forms.py
- flask_appbuilder/validators.py
- requirements/base.txt
Address WTForms 3.2 breaking change: https://github.com/pallets-eco/wtforms/blob/main/CHANGES.rst#version-320
Ref PR with the planned breaking change: https://github.com/pallets-eco/wtforms/pull/859
Error caused by FAB on WTForms:
```
AttributeError: 'tuple' object has no attribute 'items'
```
> fix: wtforms 3.2 breaking field_flags

- flask_appbuilder/security/manager.py
Adds a new config key named: `AUTH_DB_FAKE_PASSWORD_HASH_CHECK` to make it possible to configure werkzeug's hash prefix with method and interactions on the fake password hash check.
> feat: make fake password hash check configurable

- flask_appbuilder/baseviews.py
- flask_appbuilder/views.py
This refactor improves the `_get_list_widget` and `_list` methods by adding support for additional keyword arguments (**kwargs). The main changes include:
- Modified `_get_list_widget` to accept and pass **kwargs to `self.list_widget`, allowing more flexibility in handling dynamic arguments.
- Updated `_list` to accept **kwargs and pass them to `_get_list_widget`, enabling the method to adapt to various contexts where additional parameters may be required.
- These changes enhance extensibility and make the codebase more adaptable to future enhancements without needing to modify the method signatures repeatedly.
```python
widgets = self._list(custom_setting="example")
```
> refactor: enhance _get_list_widget and _list methods to accept additional kwargs

- flask_appbuilder/security/manager.py
Older version of Werkzeug use different versions of algorithms. For Apache Airflow and other potential users that are stuck with Werkzeug that is < 2.3.0 - that version does not support scrypt, so this changed caused failures with "scrypt not supported" - but if you have Werkzeug >= 2.3.0, < 3.0.0.
> fix: Default password hashing algorithm depends on Werkzeug version

- flask_appbuilder/security/manager.py
Fixes: https://github.com/dpgaspar/Flask-AppBuilder/pull/2306
on werkzeug 3.1.X the `__version__` attr does not exist anymore 
@potiuk
> fix: werkzeug version check

- bin/hash_db_password.py
- docs/config.rst
- flask_appbuilder/security/manager.py
- flask_appbuilder/security/mongoengine/manager.py
- flask_appbuilder/security/sqla/apis/user/api.py
- flask_appbuilder/security/sqla/manager.py
- flask_appbuilder/security/views.py
- tests/test_security_api.py
This is a continuation of PR #2234.
It should be noted that apart from the compliance reasons mentioned in the original PR, this change 
is also necessary for compatibility with Python <=3.9 on macOS where `hashlib.scrypt` is not available.
Two configuration options have been added: `FAB_PASSWORD_HASH_METHOD` and `FAB_PASSWORD_HASH_SALT_LENGTH`.
While `FAB_PASSWORD_HASH_SALT_LENGTH` is not strictly required for the reasons mentioned above,
I included it as there may be use cases where configuring both is needed.
> feat: Make password hashing parameters configurable

- docs/config.rst
- flask_appbuilder/utils/base.py
- tests/security/test_mvc_security.py
changes SAFE_REDIRECT_HOSTS to FAB_SAFE_REDIRECT_HOSTS
> fix: changes SAFE_REDIRECT_HOSTS to FAB_SAFE_REDIRECT_HOSTS

- flask_appbuilder/models/sqla/interface.py
Add an order by tie breaker on order by, this is specially important when paginations is used and order by is done on non unique columns
> fix: always add a unique col to ordering

- flask_appbuilder/models/filters.py
- flask_appbuilder/models/generic/filters.py
- flask_appbuilder/models/sqla/filters.py
- tests/test_api.py
This PR introduces support for the `IN` and `NOT IN` operators in filters. These operators enhance query flexibility by allowing filtering based on membership in a list of values. 
This is particularly useful for multi-select filters or scenarios requiring the exclusion of multiple values.
> feat(Filters): Add support for IN and NOT IN filter operators

- CHANGELOG.rst
- flask_appbuilder/__init__.py
> release: 4.7.0

- flask_appbuilder/api/__init__.py
- flask_appbuilder/exceptions.py
- tests/test_api.py
This PR adds support for the `select_columns` argument to the `get_headless` method.
The `select_columns` argument was initially introduced with https://github.com/dpgaspar/Flask-AppBuilder/pull/2242 to the `get_list_headless` method.
> feat: Support the select_columns arg on the Get Item method
